# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('study', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.IntegerField()),
                ('study_address', models.TextField(max_length=100)),
                ('home_address', models.TextField(max_length=100)),
                ('status_ksg', models.CharField(choices=[('gjengis', 'Gjengis'), ('funk', 'Funksjon\xe6r'), ('hangaround', 'Hangaround'), ('gjengpang', 'GjengPang'), ('funkepang', 'FunkePang'), ('hospitant', 'Hospitant')], max_length=32)),
                ('start_ksg', models.DateField(auto_now_add=True)),
                ('profile_image', models.FileField(blank=True, null=True, upload_to='profiles/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
