# Generated by Django 3.2.16 on 2022-12-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usershavemadeout",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="usershavemadeout",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
