# Generated by Django 3.2.16 on 2023-01-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_rewrite_about_me",
            field=models.BooleanField(default=True),
        ),
    ]
