# Generated by Django 3.2.16 on 2022-12-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="biography",
            new_name="about_me",
        ),
        migrations.AddField(
            model_name="user",
            name="first_time_login",
            field=models.BooleanField(default=True),
        ),
    ]
