# Generated by Django 4.2.7 on 2025-03-12 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_can_rewrite_about_me"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnightHood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("knighted_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knighthood",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
