# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-08 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170907_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
