# Generated by Django 3.2.16 on 2023-01-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_can_rewrite_about_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Themes',
                'default_related_name': 'themes',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Theme'),
        ),
    ]
