# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170921_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ksg_role',
            field=models.CharField(choices=[('gjengis', 'Gjengis'), ('funk', 'Funksjonær'), ('hangaround', 'Hangaround'), ('gjengpang', 'GjengPang'), ('funkepang', 'FunkePang'), ('hospitant', 'Hospitant')], default=('gjengis', 'Gjengis'), max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='ksg_status',
            field=models.CharField(choices=[('aktiv', 'Aktiv'), ('inaktiv', 'Ikke aktiv'), ('permittert', 'Permittert'), ('sluttet', 'Sluttet før tiden')], default=('gjengis', 'Gjengis'), max_length=32),
        ),
    ]
