# Generated by Django 4.2.7 on 2024-11-12 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_knighthood"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_revoked_ranked_consent',
            field=models.BooleanField(default=False),
        ),
    ]
