# Generated by Django 4.2.7 on 2025-03-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_knighthood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="knighthood",
            name="knighted_at",
            field=models.DateField(auto_now_add=True),
        ),
    ]
