# Generated by Django 3.2.16 on 2023-01-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230129_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='colorScheme',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
    ]
