# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170908_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='status_ksg',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='home_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='study_address',
            field=models.CharField(max_length=100),
        ),
    ]
