# Generated by Django 3.2.16 on 2022-12-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="notify_on_deposit",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_on_quote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="notify_on_shift",
            field=models.BooleanField(default=False),
        ),
    ]
