# Generated by Django 3.2.16 on 2023-01-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_theme_colorscheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='primaryShade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
