# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0001_initial'),
        ('users', '0005_auto_20171116_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='commission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holders', to='commissions.Commission'),
        ),
    ]
