# Generated by Django 3.2.16 on 2023-01-29 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_theme_primaryshade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_users', to='users.theme'),
        ),
    ]
