# Generated by Django 3.2.16 on 2023-02-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_selected_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='label',
            field=models.CharField(default='Color Label', max_length=32),
        ),
    ]
