# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='commissions.Commission'),
        ),
    ]
