# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-26 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gluten', models.BooleanField(default=False)),
                ('lactose', models.BooleanField(default=False)),
                ('milk', models.BooleanField(default=False)),
                ('nuts', models.BooleanField(default=False)),
                ('shellfish', models.BooleanField(default=False)),
                ('celery', models.BooleanField(default=False)),
                ('soy', models.BooleanField(default=False)),
                ('fish', models.BooleanField(default=False)),
                ('egg', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('pescitarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('not_swine', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'default_related_name': 'allegies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='in_relationship',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='serious_profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='allergy',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='allegies', to=settings.AUTH_USER_MODEL),
        ),
    ]
