# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-27 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180926_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergy',
            name='celery',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='egg',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='fish',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='gluten',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='lactose',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='milk',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='not_swine',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='nuts',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='pescitarian',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='shellfish',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='soy',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='user',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='vegan',
        ),
        migrations.RemoveField(
            model_name='allergy',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='allergy',
            name='name',
            field=models.CharField(choices=[('gluten', 'Glutenallergi'), ('lactose', 'Laktoseintolerant'), ('milk', 'Melkeallergi'), ('nuts', 'Nøtter'), ('shellfish', 'Skalldyr'), ('celery', 'Selleri'), ('soy', 'Soya'), ('fish', 'Fisk'), ('egg', 'Egg')], default=('gluten', 'Glutenallergi'), max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Allergy'),
        ),
    ]
