# Generated by Django 2.1.2 on 2018-11-12 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181007_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'Allergies',
                'default_related_name': 'allergies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='in_relationship',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.Allergy'),
        ),
    ]
