# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180927_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergy',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
