# Generated by Django 2.1.2 on 2018-11-17 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='use_nickname',
            field=models.BooleanField(default=False),
        ),
    ]
