# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-14 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20181003_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
