# Generated by Django 2.1.2 on 2018-11-18 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_use_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='ksg_nickname',
        ),
    ]
