# Generated by Django 2.1.2 on 2018-11-23 20:49

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181118_1327'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usershavemadeout',
            managers=[
                ('objects', users.managers.UsersHaveMadeOutManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='anonymize_in_made_out_map',
            field=models.BooleanField(default=True),
        ),
    ]
