# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-14 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
    ]
