# Generated by Django 2.1.2 on 2018-11-18 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20181118_2005'),
        ('users', '0010_auto_20181118_1258'),
    ]

    operations = [
    ]
