# Generated by Django 3.1.2 on 2020-11-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_commission'),
        ('users', '0014_auto_20201021_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holders', to='organization.commission'),
        ),
    ]
