# Generated by Django 3.1.2 on 2020-11-26 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201119_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='commission',
        ),
    ]
