# Generated by Django 3.2.16 on 2022-10-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_auto_20210303_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="needs_new_password",
            field=models.BooleanField(default=True),
        ),
    ]
