# Generated by Django 3.2.16 on 2022-10-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0016_user_migrated_from_sg"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="home_address",
            new_name="home_town",
        ),
    ]
