# Generated by Django 3.2.16 on 2022-10-24 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0017_rename_home_address_user_home_town"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.AddField(
            model_name="user",
            name="sg_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="have_made_out_with",
            field=models.ManyToManyField(
                through="users.UsersHaveMadeOut", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
