# Generated by Django 3.2.16 on 2022-10-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0018_auto_20221024_2259"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="requires_migration_wizard",
            field=models.BooleanField(default=False),
        ),
    ]
