# Generated by Django 3.2.16 on 2022-10-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0019_user_requires_migration_wizard"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
