# Generated by Django 3.2.16 on 2022-10-30 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0020_user_nickname"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "requires_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user type requires a superuser to be granted to another user.",
                    ),
                ),
                (
                    "requires_self",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this user type requires to have the permissions of the user type to grant them to another user.",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The permissions this user type grants.",
                        to="auth.Permission",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        help_text="The users having this user type.",
                        related_name="user_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserTypeLogEntry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.CharField(
                        choices=[("ADD", "Add"), ("REMOVE", "Remove")], max_length=10
                    ),
                ),
                (
                    "done_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_type_log_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_type_log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelog",
                        to="users.usertype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "User type log entries",
                "ordering": ["-timestamp"],
            },
        ),
    ]
