# Generated by Django 3.2.16 on 2022-11-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0021_usertype_usertypelogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ical_token",
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
