# Generated by Django 3.2.16 on 2022-11-03 11:36

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0022_user_ical_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="ical_token",
            field=models.CharField(
                default=users.utils.ical_token_generator, max_length=128
            ),
        ),
    ]
