# Generated by Django 3.2.16 on 2022-11-03 16:20

from django.db import migrations
from users.utils import ical_token_generator


class Migration(migrations.Migration):
    def generate_ical_token(apps, schema_editor):
        User = apps.get_model("users", "User")
        for user in User.objects.all():
            user.ical_token = ical_token_generator()
            user.save()

    dependencies = [
        ("users", "0022_user_ical_token"),
    ]

    operations = [
        migrations.RunPython(generate_ical_token, migrations.RunPython.noop),
    ]
