# Generated by Django 3.2.16 on 2022-11-04 17:32

from django.db import migrations, transaction
from users.defaults import default_user_types


class Migration(migrations.Migration):
    def create_default_user_types(apps, schema_editor):
        UserType = apps.get_model("users", "UserType")
        Permission = apps.get_model("auth", "Permission")
        with transaction.atomic():
            for user_type in default_user_types:
                print(user_type["name"])
                user_type_obj, _ = UserType.objects.get_or_create(
                    name=user_type["name"],
                    description=user_type["description"],
                    requires_self=user_type["requires_self"],
                    requires_superuser=user_type["requires_superuser"],
                )
                for permission in user_type["permissions"]:
                    # split into app label and codename
                    app_label, codename = permission.split(".")
                    permission_obj = Permission.objects.get(
                        content_type__app_label=app_label, codename=codename
                    )
                    user_type_obj.permissions.add(permission_obj)
                user_type_obj.save()

    def delete_default_user_types(apps, schema_editor):
        UserType = apps.get_model("users", "UserType")
        for user_type in default_user_types:
            user_type_obj = UserType.objects.get(name=user_type["name"])
            user_type_obj.delete()

    dependencies = [
        ("users", "0023_alter_user_ical_token"),
    ]

    operations = [
        migrations.RunPython(
            create_default_user_types, reverse_code=migrations.RunPython.noop
        ),
    ]
