# Generated by Django 3.2.5 on 2021-12-05 16:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0022_auto_20210303_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(max_length=1024)),
                ('date', models.DateField(blank=True, null=True)),
                ('max_participants', models.IntegerField(default=10)),
                ('allowed_to_join', models.ManyToManyField(related_name='events', to='organization.InternalGroupPosition')),
                ('participants', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'default_related_name': 'events',
            },
        ),
    ]
