# Generated by Django 3.2.5 on 2021-12-05 16:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(null=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
