# Generated by Django 3.2.5 on 2021-12-05 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0022_auto_20210303_1939'),
        ('events', '0002_alter_event_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='allowed_to_join',
            field=models.ManyToManyField(blank=True, related_name='events', to='organization.InternalGroupPosition'),
        ),
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
