# Generated by Django 3.2.16 on 2022-12-04 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="InternalGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("interest-group", "Interest group"),
                            ("internal-group", "Internal group"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=2048, null=True),
                ),
                (
                    "group_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="internalgroups"
                    ),
                ),
                (
                    "group_icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="internalgroups"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Internal groups",
                "default_related_name": "groups",
            },
        ),
        migrations.CreateModel(
            name="InternalGroupPosition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("available_externally", models.BooleanField(default=False)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalGroupPositionMembership",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("date_ended", models.DateField(blank=True, default=None, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("functionary", "Functionary"),
                            ("active-functionary-pang", "Active functionary pang"),
                            ("old-functionary-pang", "Old functionary pang"),
                            ("gang-member", "Gang member"),
                            ("active-gang-member-pang", "Active gang member pang"),
                            ("old-gang-member-pang", "Old gang member pang"),
                            ("interest-group-member", "Interest group member"),
                            ("hangaround", "Hangaround"),
                            ("temporary-leave", "Temporary leave"),
                        ],
                        max_length=32,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LegacyUserWorkHistory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField(blank=True, null=True)),
                ("identifying_name", models.CharField(max_length=128)),
            ],
        ),
    ]
