# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('arrangement', 'Arrangement'), ('bar', 'Bargjengen'), ('bryggeriet', 'Daglighallen mikrobryggeri'), ('daglighallen', 'Daglighallen'), ('edgar', 'Edgar'), ('lychebar', 'Lyche Bar'), ('lychekjokken', 'Lyche Kjøkken'), ('sprit', 'Spritgjengen'), ('styret', 'Styret'), ('okonomi', 'Økonomi')], max_length=32)),
                ('description', models.CharField(max_length=1024)),
                ('members', models.ManyToManyField(blank=True, related_name='internal_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Groups',
                'default_related_name': 'groups',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
