# Generated by Django 3.2.16 on 2022-12-04 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legacyuserworkhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="legacy_work_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internalgrouppositionmembership",
            name="position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memberships",
                to="organization.internalgroupposition",
            ),
        ),
        migrations.AddField(
            model_name="internalgrouppositionmembership",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_group_position_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internalgroupposition",
            name="holders",
            field=models.ManyToManyField(
                related_name="positions",
                through="organization.InternalGroupPositionMembership",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="internalgroupposition",
            name="internal_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="positions",
                to="organization.internalgroup",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="internalgroupposition",
            unique_together={("name", "internal_group")},
        ),
    ]
