# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='internalgroupposition',
            name='holders',
            field=models.ManyToManyField(blank=True, related_name='positions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='internal_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
