# Generated by Django 3.2.16 on 2023-01-10 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalgroupuserhighlight',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='internalgroupuserhighlight',
            name='description',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
