# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 18:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalGroupPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('arrangement', 'Arrangement'), ('bar', 'Bargjengen'), ('bryggeriet', 'Daglighallen mikrobryggeri'), ('daglighallen', 'Daglighallen'), ('edgar', 'Edgar'), ('lychebar', 'Lyche Bar'), ('lychekjokken', 'Lyche Kjøkken'), ('sprit', 'Spritgjengen'), ('styret', 'Styret'), ('okonomi', 'Økonomi')], max_length=32, unique=True)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='internalgroup',
            options={'verbose_name_plural': 'Internal groups'},
        ),
        migrations.AlterField(
            model_name='internalgroup',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='internalgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='internal_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='internalgroup',
            name='name',
            field=models.CharField(choices=[('arrangement', 'Arrangement'), ('bar', 'Bargjengen'), ('bryggeriet', 'Daglighallen mikrobryggeri'), ('daglighallen', 'Daglighallen'), ('edgar', 'Edgar'), ('lychebar', 'Lyche Bar'), ('lychekjokken', 'Lyche Kjøkken'), ('sprit', 'Spritgjengen'), ('styret', 'Styret'), ('okonomi', 'Økonomi')], max_length=32, unique=True),
        ),
    ]
