# Generated by Django 3.2.16 on 2022-12-14 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyUserWorkHistory",
        ),
    ]
