# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20171116_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalgroupposition',
            name='name',
            field=models.CharField(choices=[('arrangementsansvarlig', 'Arrangementsansvarlig'), ('arrangementsbartender', 'Arrangementsbartender'), ('barsjef', 'Barsjef'), ('bartender', 'Bartender'), ('bryggfunk', 'Bryggfunk'), ('brygger', 'Brygger'), ('daglighallenfunk', 'Daglighallenfunk'), ('daglighallenfunk', 'Daglighallenbartender'), ('kafeansvarlig', 'Kaféansvarlig'), ('baristaer', 'Barista'), ('hovmester', 'Hovmester'), ('barservitor', 'Barservitør'), ('souschef', 'Souschef'), ('kokk', 'Kokk'), ('spritbarsjef', 'Spritbarsjef'), ('spritbartender', 'Spritbartender'), ('styret', 'Styret'), ('okonomi', 'Økonomi')], max_length=32, unique=True),
        ),
    ]
