# Generated by Django 3.2.16 on 2022-12-14 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0003_delete_legacyuserworkhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalgroup",
            name="highlighted_name",
            field=models.CharField(default="Funksjonærene", max_length=32),
        ),
        migrations.CreateModel(
            name="InternalGroupUserHighlight",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="internalgroups"
                    ),
                ),
                ("archived", models.BooleanField(default=False)),
                (
                    "internal_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_highlights",
                        to="organization.internalgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_group_highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
