# Generated by Django 3.2.16 on 2022-12-29 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_auto_20221214_1921"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalgroup",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="internalgroupposition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="internalgrouppositionmembership",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="internalgroupuserhighlight",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
