# Generated by Django 2.1.2 on 2018-10-07 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180201_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='internalgroup',
            options={'default_related_name': 'groups', 'verbose_name_plural': 'Internal groups'},
        ),
    ]
