# Generated by Django 2.2 on 2019-04-22 16:27

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20181007_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalgroup',
            name='name',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='arrangement', max_length=100, no_check_for_status=True, unique=True),
        ),
        migrations.AlterField(
            model_name='internalgroupposition',
            name='name',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='arrangementsansvarlig', max_length=100, no_check_for_status=True, unique=True),
        ),
    ]
