# Generated by Django 3.1.2 on 2020-11-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_auto_20190422_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalgroup',
            name='name',
            field=models.CharField(choices=[('arrangement', 'Arrangement'), ('bar', 'Bargjengen'), ('bryggeriet', 'Daglighallen mikrobryggeri'), ('daglighallen', 'Daglighallen'), ('edgar', 'Edgar'), ('lychebar', 'Lyche Bar'), ('lychekjokken', 'Lyche Kjøkken'), ('sprit', 'Spritgjengen'), ('styret', 'Styret'), ('okonomi', 'Økonomi')], max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='internalgroupposition',
            name='name',
            field=models.CharField(choices=[('arrangementsansvarlig', 'Arrangementsansvarlig'), ('arrangementsbartender', 'Arrangementsbartender'), ('barsjef', 'Barsjef'), ('bartender', 'Bartender'), ('bryggfunk', 'Bryggfunk'), ('brygger', 'Brygger'), ('daglighallenfunk', 'Daglighallenfunk'), ('daglighallenbartender', 'Daglighallenbartender'), ('kafeansvarlig', 'Kaféansvarlig'), ('baristaer', 'Barista'), ('hovmester', 'Hovmester'), ('barservitor', 'Barservitør'), ('souschef', 'Souschef'), ('kokk', 'Kokk'), ('spritbarsjef', 'Spritbarsjef'), ('spritbartender', 'Spritbartender'), ('styret', 'Styret'), ('okonomi', 'Økonomi')], max_length=32, unique=True),
        ),
    ]
