# Generated by Django 3.1.2 on 2020-11-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20201114_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalgroup',
            name='type',
            field=models.CharField(choices=[('interest-group', 'Interest Group'), ('internal-group', 'Internal Group')], default='internal-group', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalgroup',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
