# Generated by Django 3.1.2 on 2020-11-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20201114_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalgroupposition',
            name='internal_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='organization.internalgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internalgroupposition',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
