# Generated by Django 3.1.2 on 2020-12-04 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0011_commission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internalgroup',
            name='members',
        ),
        migrations.AddField(
            model_name='commission',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='organization.internalgroupposition'),
        ),
        migrations.AlterField(
            model_name='internalgroup',
            name='description',
            field=models.TextField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='internalgroupposition',
            name='internal_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='organization.internalgroup'),
        ),
        migrations.AlterUniqueTogether(
            name='internalgroupposition',
            unique_together={('name', 'internal_group')},
        ),
        migrations.CreateModel(
            name='InternalGroupPositionMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('date_ended', models.DateField(blank=True, default=None, null=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='organization.internalgroupposition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ManyToManyField(related_name='committees', to='organization.Commission')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(auto_now_add=True)),
                ('date_ended', models.DateField(blank=True, default=None, null=True)),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memberships', to='organization.commission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='commission',
            name='holders',
            field=models.ManyToManyField(related_name='comissions', through='organization.CommissionMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internalgroupposition',
            name='holders',
            field=models.ManyToManyField(related_name='positions', through='organization.InternalGroupPositionMembership', to=settings.AUTH_USER_MODEL),
        ),
    ]
