# Generated by Django 3.1.2 on 2021-01-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_auto_20210117_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalgroupposition',
            name='type',
            field=models.CharField(choices=[('functionary', 'Functionary'), ('gang-member', 'Gang Member'), ('interest-group-member', 'Interest Group Member'), ('active-functionary-pang', 'Active Functionary Pang'), ('old-functionary-pang', 'Old Functionary Pang'), ('active-gang-member-pang', 'Active Gang Member Pang'), ('old-gang-member-pang', 'Old Gang Member Pang'), ('hangaround', 'Hangaround')], default='gang-member', max_length=32),
            preserve_default=False,
        ),
    ]
