# Generated by Django 3.1.2 on 2021-01-17 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_internalgroupposition_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='manager',
        ),
    ]
