# Generated by Django 3.1.2 on 2021-01-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_remove_commission_manager'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='internalgroupposition',
            unique_together={('name', 'internal_group', 'type')},
        ),
    ]
