# Generated by Django 3.1.2 on 2021-02-04 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_internalgroup_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalgrouppositionmembership',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
