# Generated by Django 3.1.6 on 2021-02-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0019_auto_20210209_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalgroup",
            name="type",
            field=models.CharField(
                choices=[
                    ("interest-group", "Interest group"),
                    ("internal-group", "Internal group"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="internalgroupposition",
            name="type",
            field=models.CharField(
                choices=[
                    ("functionary", "Functionary"),
                    ("active-functionary-pang", "Active functionary pang"),
                    ("old-functionary-pang", "Old functionary pang"),
                    ("gang-member", "Gang member"),
                    ("active-gang-member-pang", "Active gang member pang"),
                    ("old-gang-member-pang", "Old gang member pang"),
                    ("interest-group-member", "Interest group member"),
                    ("hangaround", "Hangaround"),
                ],
                max_length=32,
            ),
        ),
    ]
