# Generated by Django 3.1.7 on 2021-03-03 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0021_auto_20210210_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internalgrouppositionmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_group_position_history', to=settings.AUTH_USER_MODEL),
        ),
    ]
