# Generated by Django 3.2 on 2021-04-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0022_auto_20210303_1939"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalgroupposition",
            name="type",
            field=models.CharField(
                choices=[
                    ("functionary", "Functionary"),
                    ("active-functionary-pang", "Active functionary pang"),
                    ("old-functionary-pang", "Old functionary pang"),
                    ("gang-member", "Gang member"),
                    ("old-gang-member", "Old gang member"),
                    ("active-gang-member-pang", "Active gang member pang"),
                    ("old-gang-member-pang", "Old gang member pang"),
                    ("interest-group-member", "Interest group member"),
                    ("hangaround", "Hangaround"),
                    ("temporary-leave", "Temporary leave"),
                ],
                max_length=32,
            ),
        ),
    ]
