# Generated by Django 3.2.5 on 2021-11-22 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_auto_20210303_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalgroup',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
