# Generated by Django 3.2.12 on 2022-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0023_auto_20220130_2056"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalgroupposition",
            name="available_externally",
            field=models.BooleanField(default=False),
        ),
    ]
