# Generated by Django 3.2.12 on 2022-03-08 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0030_alter_applicant_status"),
        ("organization", "0024_internalgroupposition_available_externally"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalgroup",
            name="currently_discussing",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="groups",
                to="admissions.applicant",
            ),
        ),
    ]
