# Generated by Django 3.2.12 on 2022-03-26 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0025_internalgroup_currently_discussing"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="internalgroup",
            name="currently_discussing",
        ),
    ]
