# Generated by Django 3.2.12 on 2022-04-26 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0026_remove_internalgroup_currently_discussing"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalgroup",
            name="group_icon",
            field=models.ImageField(blank=True, null=True, upload_to="internalgroups"),
        ),
    ]
