# Generated by Django 3.2.16 on 2022-10-26 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0027_internalgroup_group_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commissionmembership",
            name="commission",
        ),
        migrations.RemoveField(
            model_name="commissionmembership",
            name="user",
        ),
        migrations.RemoveField(
            model_name="committee",
            name="members",
        ),
        migrations.DeleteModel(
            name="Commission",
        ),
        migrations.DeleteModel(
            name="CommissionMembership",
        ),
        migrations.DeleteModel(
            name="Committee",
        ),
    ]
