# Generated by Django 4.2.7 on 2026-07-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handbook', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='highlighted',
            field=models.BooleanField(default=False),
        ),
    ]
