# Generated by Django 3.2.16 on 2022-12-04 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BarTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_opened", models.DateTimeField(auto_now_add=True)),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                ("datetime_reviewed", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Open"),
                            ("LOCKED", "Locked"),
                            ("UNDER_REVIEW", "Under review"),
                            ("REVIEWED", "Reviewed"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarTabCustomer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=32)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name="BarTabProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="BarTabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("BONG", "Bong"), ("LIST", "List")], max_length=4
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "away",
                    models.BooleanField(
                        default=False,
                        help_text="If true this is us at another 'customer'",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("cost", models.IntegerField()),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "bar_tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="bar_tab.bartab",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="bar_tab.bartabcustomer",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="bar_tab.bartabproduct",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BarTabInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField(auto_now_add=True)),
                ("datetime_sent", models.DateTimeField(blank=True, null=True)),
                ("datetime_settled", models.DateTimeField(blank=True, null=True)),
                ("we_owe", models.IntegerField()),
                ("they_owe", models.IntegerField()),
                (
                    "amount",
                    models.IntegerField(help_text="Negative values indicate a refund"),
                ),
                (
                    "pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="bar_tab/invoices"
                    ),
                ),
                (
                    "bar_tab",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="bar_tab.bartab",
                    ),
                ),
            ],
        ),
    ]
