# Generated by Django 3.2.18 on 2023-03-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bar_tab", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartabcustomer",
            name="webhook_url",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
