# Generated by Django 3.2.16 on 2022-10-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdodbLogsql",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField()),
                ("sql0", models.CharField(max_length=250)),
                ("sql1", models.TextField()),
                ("params", models.TextField()),
                ("tracer", models.TextField()),
                ("timer", models.DecimalField(decimal_places=6, max_digits=16)),
            ],
            options={
                "db_table": "adodb_logsql",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Arrangementer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dato", models.DateField()),
                ("tittel", models.TextField(blank=True, null=True)),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("bestillernavn", models.TextField(blank=True, null=True)),
                ("bestillertelefon", models.TextField(blank=True, null=True)),
                ("starttid", models.IntegerField(blank=True, null=True)),
                ("stopptid", models.IntegerField(blank=True, null=True)),
                ("aapningstid", models.TimeField(blank=True, null=True)),
                ("stengetid", models.TimeField(blank=True, null=True)),
                ("oppmote", models.DurationField(blank=True, null=True)),
                ("omsetning", models.IntegerField(blank=True, null=True)),
                ("erfaringer", models.TextField(blank=True, null=True)),
                ("stengetid_synlig", models.BooleanField()),
            ],
            options={
                "db_table": "Arrangementer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Barer",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("navn", models.TextField(blank=True, null=True)),
                ("kortnavn", models.TextField(blank=True, null=True)),
                ("rekkefolge", models.IntegerField(blank=True, null=True)),
                ("robokopid", models.IntegerField(blank=True, null=True)),
                ("limid", models.IntegerField(blank=True, null=True)),
                ("oppmote", models.DurationField()),
            ],
            options={
                "db_table": "Barer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bartyper",
            fields=[
                ("id", models.TextField(primary_key=True, serialize=False)),
                ("navn", models.TextField()),
            ],
            options={
                "db_table": "Bartyper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bildefavoritter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album", models.TextField()),
                ("bilde", models.TextField()),
                ("person", models.IntegerField()),
            ],
            options={
                "db_table": "Bildefavoritter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bildekommentarer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album", models.CharField(max_length=40)),
                ("bilde", models.CharField(max_length=100)),
                ("tekst", models.TextField()),
                ("registrert", models.DateTimeField()),
            ],
            options={
                "db_table": "Bildekommentarer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bilderpersoner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album", models.CharField(max_length=40)),
                ("bilde", models.CharField(max_length=100)),
                ("person", models.IntegerField()),
            ],
            options={
                "db_table": "BilderPersoner",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bsf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registrert", models.DateTimeField()),
                ("beskrivelse", models.TextField()),
                ("publisert", models.BooleanField()),
                ("stengt", models.BooleanField()),
            ],
            options={
                "db_table": "BSF",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bsfgjenger",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("gjengnavn", models.TextField()),
                ("hybelnavn", models.TextField()),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("saldo", models.FloatField()),
            ],
            options={
                "db_table": "BSFGjenger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bsfkryssborte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("belop", models.FloatField()),
                ("registrert", models.DateTimeField(blank=True, null=True)),
                ("kommentar", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "BSFKryssBorte",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bsfkrysshjemme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("person", models.TextField()),
                ("belop", models.FloatField()),
                ("registrert", models.DateTimeField(blank=True, null=True)),
                ("kommentar", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "BSFKryssHjemme",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bsfoverforinger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("belop", models.FloatField()),
                ("registrert", models.DateTimeField()),
                ("kommentar", models.TextField()),
            ],
            options={
                "db_table": "BSFOverforinger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                ("tid", models.DateTimeField(primary_key=True, serialize=False)),
                ("person", models.IntegerField()),
                ("melding", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "Chat",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Ekstern",
            fields=[
                (
                    "navn",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("tittel", models.CharField(blank=True, max_length=100, null=True)),
                ("tekst", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "_Ekstern",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Galleri",
            fields=[
                (
                    "id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("tittel", models.TextField()),
                ("tekst", models.TextField()),
                ("tid", models.DateTimeField(blank=True, null=True)),
                ("knipsetid", models.DateField(blank=True, null=True)),
                ("publisert", models.BooleanField()),
                ("godkjent", models.BooleanField()),
            ],
            options={
                "db_table": "Galleri",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Gammelpersoner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "personid",
                    models.IntegerField(blank=True, db_column="PersonID", null=True),
                ),
                (
                    "gjengid",
                    models.IntegerField(blank=True, db_column="GjengID", null=True),
                ),
                ("navn", models.TextField(blank=True, db_column="Navn", null=True)),
                ("kortnr", models.TextField(blank=True, db_column="Kortnr", null=True)),
                ("saldo", models.FloatField(blank=True, db_column="Saldo", null=True)),
                (
                    "saldodato",
                    models.TextField(blank=True, db_column="SaldoDato", null=True),
                ),
                ("email", models.TextField(blank=True, db_column="Email", null=True)),
                (
                    "sistsjekket",
                    models.TextField(blank=True, db_column="SistSjekket", null=True),
                ),
                (
                    "socikryss",
                    models.IntegerField(blank=True, db_column="SociKryss", null=True),
                ),
                (
                    "uglekryss",
                    models.IntegerField(blank=True, db_column="UgleKryss", null=True),
                ),
                (
                    "huskryss",
                    models.IntegerField(blank=True, db_column="HusKryss", null=True),
                ),
                (
                    "stilletimekryss",
                    models.IntegerField(
                        blank=True, db_column="StilleTimeKryss", null=True
                    ),
                ),
                (
                    "kryssenavn",
                    models.TextField(blank=True, db_column="KrysseNavn", null=True),
                ),
                (
                    "adminnivå",
                    models.IntegerField(blank=True, db_column="AdminNivå", null=True),
                ),
                (
                    "passord",
                    models.TextField(blank=True, db_column="Passord", null=True),
                ),
                (
                    "gammeltkryssenavn",
                    models.TextField(
                        blank=True, db_column="GammeltKrysseNavn", null=True
                    ),
                ),
            ],
            options={
                "db_table": "_GammelPersoner",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grupper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField(blank=True, null=True)),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("historikk", models.BooleanField()),
                ("aktiv", models.BooleanField()),
                ("stillingsnavn", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Grupper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Grupperhistorikk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fradato", models.DateField()),
                ("tildato", models.DateField(blank=True, null=True)),
                ("merknad", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "GrupperHistorikk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Innkryssinger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registrert", models.DateTimeField()),
                ("kryssetid", models.DateTimeField()),
                ("kommentar", models.TextField(blank=True, null=True)),
                ("lukket", models.BooleanField()),
            ],
            options={
                "db_table": "Innkryssinger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Innskudd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registrert", models.DateTimeField()),
                ("penger", models.FloatField()),
                ("type", models.CharField(max_length=1)),
                ("godkjent", models.BooleanField()),
                ("kommentar", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Innskudd",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Intervjuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField()),
                ("adresse", models.TextField()),
                ("hjemadresse", models.TextField()),
                ("studie", models.TextField()),
                ("fodselsdato", models.DateField()),
                ("tattopp", models.BooleanField()),
                ("telefon", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("by", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Intervjuer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Jubileum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField(blank=True, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("telefon", models.TextField(blank=True, null=True)),
                ("kontonummer", models.TextField(blank=True, null=True)),
                ("begyntesg", models.TextField(blank=True, null=True)),
                ("studie", models.TextField(blank=True, null=True)),
                ("verv", models.TextField(blank=True, null=True)),
                ("notater", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "_jubileum",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Kryss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kryssetid", models.DateTimeField(blank=True, null=True)),
                ("antall", models.FloatField()),
                ("pris", models.FloatField()),
            ],
            options={
                "db_table": "Kryss",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tittel", models.TextField(blank=True, null=True)),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("sql", models.TextField(blank=True, null=True)),
                ("tommefelter", models.TextField(blank=True, null=True)),
                ("type", models.TextField(blank=True, null=True)),
                ("tekst", models.TextField(blank=True, null=True)),
                ("synlig", models.BooleanField()),
            ],
            options={
                "db_table": "Lister",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Logg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("starttid", models.DateTimeField()),
                ("stopptid", models.DateTimeField()),
                ("ip", models.TextField(blank=True, null=True)),
                ("useragent", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "logg",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoggSider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(unique=True)),
                ("tittel", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "logg_sider",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LoggSiderTreff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "logg_sider_treff",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Opptak",
            fields=[
                (
                    "id",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("lukket", models.BooleanField()),
                ("kommentar", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Opptak",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Overforinger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("belop", models.IntegerField()),
                ("kommentar", models.TextField(blank=True, null=True)),
                ("registrert", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "Overforinger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Paameldinger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tittel", models.TextField()),
                ("tekst", models.TextField()),
                ("maksantall", models.IntegerField(blank=True, null=True)),
                ("startdato", models.DateTimeField()),
                ("sluttdato", models.DateTimeField()),
                ("stengt", models.BooleanField(blank=True, null=True)),
            ],
            options={
                "db_table": "Paameldinger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Paameldingergrupper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "PaameldingerGrupper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Paameldingerpersoner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "PaameldingerPersoner",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Paameldingerstatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "PaameldingerStatus",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pengekasseoverforinger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("belop", models.IntegerField()),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("tid", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "PengekasseOverforinger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Pengekasser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField()),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("saldo", models.IntegerField()),
            ],
            options={
                "db_table": "Pengekasser",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Personer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.TextField(blank=True, null=True, unique=True)),
                ("passord", models.CharField(max_length=32)),
                ("kortnummer", models.CharField(blank=True, max_length=10, null=True)),
                ("navn", models.TextField(blank=True, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("hjemstedsadresse", models.TextField(blank=True, null=True)),
                ("studie", models.TextField(blank=True, null=True)),
                ("fodselsdato", models.DateField(blank=True, null=True)),
                ("telefon", models.TextField(blank=True, null=True)),
                ("begynte", models.CharField(blank=True, max_length=6, null=True)),
                ("saldo", models.FloatField()),
                ("sistonline", models.DateTimeField(blank=True, null=True)),
                ("login", models.TextField(blank=True, null=True)),
                ("by", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Personer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Quizfolk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("treff", models.BooleanField()),
            ],
            options={
                "db_table": "QuizFolk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Quizresultater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.TextField()),
                ("resultat", models.FloatField()),
                ("tid", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "QuizResultater",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Referater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dato", models.DateField()),
                ("tittel", models.TextField()),
                ("tilstede", models.TextField()),
                ("innhold", models.TextField()),
                ("registrert", models.DateTimeField()),
            ],
            options={
                "db_table": "Referater",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sider",
            fields=[
                ("kategori", models.CharField(max_length=30)),
                (
                    "navn",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("tittel", models.CharField(blank=True, max_length=100, null=True)),
                ("tekst", models.TextField(blank=True, null=True)),
                ("html", models.BooleanField()),
            ],
            options={
                "db_table": "Sider",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sidetider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("side", models.TextField()),
                ("tid", models.FloatField()),
            ],
            options={
                "db_table": "_SideTider",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Sitater",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tid", models.DateTimeField()),
                ("tekst", models.TextField()),
                ("godkjent", models.BooleanField()),
            ],
            options={
                "db_table": "Sitater",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Socisanger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tid", models.DateTimeField(unique=True)),
                ("url", models.TextField()),
                ("tittel", models.TextField()),
            ],
            options={
                "db_table": "Socisanger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Soknader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField()),
                ("telefon", models.TextField()),
                ("email", models.TextField()),
            ],
            options={
                "db_table": "Soknader",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.CharField(max_length=15, primary_key=True, serialize=False),
                ),
                ("navn", models.TextField(blank=True, null=True)),
                ("beskrivelse", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Statushistorikk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fradato", models.DateField()),
                ("tildato", models.DateField(blank=True, null=True)),
                ("merknad", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "StatusHistorikk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tempgammelny",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gammel", models.IntegerField()),
                ("ny", models.IntegerField()),
            ],
            options={
                "db_table": "_TempGammelNy",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tilganger",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("tittel", models.TextField()),
                ("beskrivelse", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Tilganger",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vakter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notified", models.BooleanField()),
            ],
            options={
                "db_table": "Vakter",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vaktonske",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("arrangement_id", models.IntegerField()),
                ("person_id", models.IntegerField()),
                ("status", models.CharField(blank=True, max_length=20, null=True)),
                ("type", models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                "db_table": "Vaktonske",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VaktonskeArrangement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aapn_dato", models.DateField(blank=True, null=True)),
                ("onskbar", models.BooleanField()),
            ],
            options={
                "db_table": "Vaktonske_arrangement",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vakttyper",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("navn", models.TextField()),
                ("kortnavn", models.TextField()),
                ("color", models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                "db_table": "Vakttyper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Varer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField(blank=True, null=True)),
                ("beskrivelse", models.TextField(blank=True, null=True)),
                ("pris", models.FloatField()),
                ("andrepris", models.FloatField()),
                ("bokstav", models.CharField(blank=True, max_length=1, null=True)),
                ("bildenavn", models.CharField(blank=True, max_length=30, null=True)),
                ("liter", models.FloatField(blank=True, null=True)),
                ("volumprosent", models.FloatField(blank=True, null=True)),
                ("synlig", models.BooleanField()),
                ("pricelist", models.BooleanField()),
            ],
            options={
                "db_table": "Varer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Verv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("navn", models.TextField()),
                ("aktiv", models.BooleanField()),
            ],
            options={
                "db_table": "Verv",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Vervhistorikk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fradato", models.DateField()),
                ("tildato", models.DateField(blank=True, null=True)),
                ("merknad", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "VervHistorikk",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Bartypervakttyper",
            fields=[
                (
                    "bartype",
                    models.OneToOneField(
                        db_column="bartype",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="legacy.bartyper",
                    ),
                ),
            ],
            options={
                "db_table": "BartyperVakttyper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Personergrupper",
            fields=[
                (
                    "personid",
                    models.OneToOneField(
                        db_column="personid",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="legacy.personer",
                    ),
                ),
            ],
            options={
                "db_table": "PersonerGrupper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tilgangergrupper",
            fields=[
                (
                    "tilgang",
                    models.OneToOneField(
                        db_column="tilgang",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="legacy.tilganger",
                    ),
                ),
            ],
            options={
                "db_table": "TilgangerGrupper",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Tilgangerstatus",
            fields=[
                (
                    "tilgang",
                    models.OneToOneField(
                        db_column="tilgang",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="legacy.tilganger",
                    ),
                ),
            ],
            options={
                "db_table": "TilgangerStatus",
                "managed": False,
            },
        ),
    ]
