# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('ot', 'Other summary'), ('ka', 'Kafeansvarlig summary'), ('hm', 'Hovmester summary'), ('bs', 'Barsjef summary'), ('sc', 'Souschef summary'), ('ar', 'Arrangement summary'), ('ok', 'Økonomi summary'), ('st', 'Styret summary'), ('kit', 'KSG-IT summary')], default='ot', max_length=4)),
                ('contents', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, related_name='summaries', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
                'default_related_name': 'summaries',
            },
        ),
    ]
