# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-10-03 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('other', 'Other summary'), ('kafeansvarlig', 'Kafeansvarlig summary'), ('hovmester', 'Hovmester summary'), ('barsjef', 'Barsjef summary'), ('souschef', 'Souschef summary'), ('arrangement', 'Arrangement summary'), ('okonomi', 'Økonomi summary'), ('styret', 'Styret summary'), ('kit', 'KSG-IT summary')], default='other', max_length=16)),
                ('contents', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
                ('participants', models.ManyToManyField(blank=True, related_name='summaries', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_summaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Summaries',
                'default_related_name': 'summaries',
            },
        ),
    ]
