# Generated by Django 2.1.2 on 2018-11-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary_type',
            field=models.CharField(choices=[('other', 'Other summary'), ('kafeansvarlig', 'Kafeansvarlig summary'), ('hovmester', 'Hovmester summary'), ('barsjef', 'Barsjef summary'), ('souschef', 'Souschef summary'), ('arrangement', 'Arrangement summary'), ('okonomi', 'Økonomi summary'), ('styret', 'Styret summary'), ('drift', 'Drift summary'), ('daglighallen', 'Daglighallen summary'), ('kit', 'KSG-IT summary')], default='other', max_length=16),
        ),
    ]
