# Generated by Django 4.2.3 on 2023-08-16 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0003_auto_20230110_1123"),
        ("summaries", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="internal_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organization.internalgroup",
            ),
        ),
    ]
