# Generated by Django 2.1.2 on 2018-11-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_auto_20181112_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='summary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
