# Generated by Django 2.2 on 2019-04-22 16:52

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_auto_20181112_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='summary',
            name='summary_type',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='other', max_length=16, no_check_for_status=True),
        ),
    ]
