# Generated by Django 3.2.9 on 2021-12-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0004_summary_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="summary_type",
            field=models.CharField(
                choices=[
                    ("annet", "Annet"),
                    ("kafeansvarlig", "Kafeansvarlig"),
                    ("hovmester", "Hovmester"),
                    ("barsjef", "Barsjef"),
                    ("souschef", "Souschef"),
                    ("arrangement", "Arrangement"),
                    ("okonomi", "Økonomi"),
                    ("styret", "Styret"),
                    ("drift", "Drift"),
                    ("daglighallen", "Daglighallen"),
                    ("kit", "KSG-IT"),
                ],
                max_length=32,
            ),
        ),
    ]
