# Generated by Django 3.2.11 on 2022-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0006_rename_summary_type_summary_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="type",
            field=models.CharField(
                choices=[
                    ("annet", "Annet"),
                    ("kafeansvarlig", "Kafeansvarlig"),
                    ("hovmester", "Hovmester"),
                    ("barsjef", "Barsjef"),
                    ("spritbarsjef", "Spritbarsjef"),
                    ("souschef", "Souschef"),
                    ("arrangement", "Arrangement"),
                    ("okonomi", "Økonomi"),
                    ("styret", "Styret"),
                    ("drift", "Drift"),
                    ("daglighallen", "Daglighallen"),
                    ("kit", "KSG-IT"),
                ],
                max_length=32,
            ),
        ),
    ]
