# Generated by Django 3.2.16 on 2022-10-25 21:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("summaries", "0008_legacysummary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="legacysummary",
            options={
                "default_related_name": "legacy_summaries",
                "verbose_name_plural": "Legacy Summaries",
            },
        ),
        migrations.AlterField(
            model_name="legacysummary",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="legacy_summaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
