# Generated by Django 3.2.16 on 2022-10-30 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("summaries", "0009_auto_20221025_2303"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="reporter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reported_summaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
