# Generated by Django 3.2.16 on 2022-11-08 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0010_alter_summary_reporter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="type",
            field=models.CharField(
                choices=[
                    ("ANNET", "Annet"),
                    ("KAFEANSVARLIG", "Kafeansvarlig"),
                    ("HOVMESTER", "Hovmester"),
                    ("BARSJEF", "Barsjef"),
                    ("SPRITBARSJEF", "Spritbarsjef"),
                    ("SOUSCHEF", "Souschef"),
                    ("ARRANGEMENT", "Arrangement"),
                    ("OKONOMI", "Økonomi"),
                    ("STYRET", "Styret"),
                    ("DRIFT", "Drift"),
                    ("DAGLIGHALLEN", "Daglighallen"),
                    ("KIT", "KSG-IT"),
                ],
                max_length=32,
            ),
        ),
    ]
