# Generated by Django 3.2.16 on 2022-11-10 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0029_legacyuserworkhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("summaries", "0011_alter_summary_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="summary",
            name="type",
        ),
        migrations.AddField(
            model_name="summary",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="summary",
            name="internal_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="summaries",
                to="organization.internalgroup",
            ),
        ),
        migrations.AddField(
            model_name="summary",
            name="title",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="summary",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="meetings_attended_summaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="LegacySummary",
        ),
    ]
