# Generated by Django 3.2.16 on 2022-11-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0012_auto_20221110_1613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="summary",
            name="date",
            field=models.DateField(),
        ),
    ]
