# Generated by Django 3.2.5 on 2021-12-01 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solution_in_quiz', to=settings.AUTH_USER_MODEL)),
                ('guessed_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clicked_in_quiz', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_users', models.ManyToManyField(related_name='quiz_fakes', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='related_quiz', through='quiz.Participant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_in_quiz', to='quiz.quiz'),
        ),
    ]
