# Generated by Django 3.2.5 on 2021-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='identifier',
            field=models.CharField(blank=True, choices=[('lyche-bar', 'Lyche Bar'), ('lyche-kitchen', 'Lyche Kjøkken'), ('bar', 'Bar'), ('sprit', 'Spritgjengen'), ('arrangement', 'Arrangement'), ('daglighallen', 'Daglighallen Bar')], max_length=20, null=True, unique=True),
        ),
    ]
