# Generated by Django 3.2.5 on 2021-12-02 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_started',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
