# Generated by Django 3.2.5 on 2021-09-23 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='identifier',
            field=models.CharField(blank=True, choices=[('edgar', 'Edgar'), ('lyche-bar', 'Lyche Bar'), ('lyche-kitchen', 'Lyche Kjøkken'), ('bar', 'Bar'), ('sprit', 'Spritgjengen'), ('arrangement', 'Arrangement'), ('daglighallen', 'Daglighallen Bar')], max_length=20, null=True),
        ),
    ]
