# Generated by Django 3.2.5 on 2021-12-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20211202_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='final_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
