# Generated by Django 3.2.5 on 2021-12-02 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0003_quiz_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='user_quizzed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_taking_quiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
