# Generated by Django 3.2.5 on 2021-11-22 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0004_alter_participant_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='solution',
            new_name='guessed',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='relation',
            new_name='quiz',
        ),
        migrations.AddField(
            model_name='participant',
            name='guessed_correctly',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
