# Generated by Django 3.2.5 on 2021-11-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20211122_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_correct',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_progress',
        ),
    ]
