# Generated by Django 3.2.5 on 2021-11-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_auto_20211125_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_quiz', to='quiz.quiz'),
        ),
    ]
