# Generated by Django 3.2.5 on 2021-11-26 15:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0009_auto_20211126_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='fake_users',
            field=models.ManyToManyField(related_name='quiz_fakes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='quiz.quiz'),
        ),
    ]
