# Generated by Django 3.2.5 on 2021-11-26 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_auto_20211126_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='participant',
            new_name='participants',
        ),
        migrations.AlterField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quiz'),
        ),
    ]
