# Generated by Django 3.2.5 on 2021-11-27 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0011_auto_20211126_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='quiz_question',
        ),
        migrations.AlterField(
            model_name='participant',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants_in_quiz', to='quiz.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='related_quiz', through='quiz.Participant', to=settings.AUTH_USER_MODEL),
        ),
    ]
