# Generated by Django 2.1.5 on 2019-04-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensormeasurement',
            name='type',
            field=models.CharField(choices=[('temperature', 'Temperature'), ('humidity', 'Humidity'), ('sound', 'Sound'), ('people', 'People count')], max_length=16),
        ),
    ]
