# Generated by Django 2.2.7 on 2020-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slideshow/')),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField()),
                ('start_datetime', models.DateField()),
                ('end_datetime', models.DateField()),
            ],
        ),
    ]
