# Generated by Django 3.2.16 on 2022-11-27 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("internal", "0002_slideshowimage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Commission",
        ),
        migrations.DeleteModel(
            name="SlideshowImage",
        ),
    ]
