# Generated by Django 2.2.7 on 2020-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internal', '0002_slideshow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideshow',
            name='end_datetime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='slideshow',
            name='start_datetime',
            field=models.DateTimeField(),
        ),
    ]
