# Generated by Django 3.2.16 on 2023-01-03 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admissions", "0001_initial"),
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="interviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="interviews_attended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.interviewlocation",
            ),
        ),
        migrations.AddField(
            model_name="internalgrouppositionpriority",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priorities",
                to="admissions.applicant",
            ),
        ),
        migrations.AddField(
            model_name="internalgrouppositionpriority",
            name="internal_group_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_priorities",
                to="organization.internalgroupposition",
            ),
        ),
        migrations.AddField(
            model_name="applicantunavailability",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unavailability",
                to="admissions.applicant",
            ),
        ),
        migrations.AddField(
            model_name="applicantinterest",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="internal_group_interests",
                to="admissions.applicant",
            ),
        ),
        migrations.AddField(
            model_name="applicantinterest",
            name="internal_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_interests",
                to="organization.internalgroup",
            ),
        ),
        migrations.AddField(
            model_name="applicantinterest",
            name="position_to_be_offered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_interest_offers",
                to="organization.internalgroupposition",
            ),
        ),
        migrations.AddField(
            model_name="applicantcomment",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="admissions.applicant",
            ),
        ),
        migrations.AddField(
            model_name="applicantcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicants",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="interview",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant",
                to="admissions.interview",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="notice_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="admissionavailableinternalgrouppositiondata",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_internal_group_positions_data",
                to="admissions.admission",
            ),
        ),
        migrations.AddField(
            model_name="admissionavailableinternalgrouppositiondata",
            name="internal_group_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organization.internalgroupposition",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="available_internal_group_positions",
            field=models.ManyToManyField(
                through="admissions.AdmissionAvailableInternalGroupPositionData",
                to="organization.InternalGroupPosition",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interviewbooleanevaluationanswer",
            unique_together={("interview", "statement")},
        ),
        migrations.AlterUniqueTogether(
            name="interviewadditionalevaluationanswer",
            unique_together={("interview", "statement")},
        ),
        migrations.AlterUniqueTogether(
            name="interview",
            unique_together={("interview_start", "interview_end", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="internalgrouppositionpriority",
            unique_together={("applicant", "applicant_priority")},
        ),
        migrations.AlterUniqueTogether(
            name="admissionavailableinternalgrouppositiondata",
            unique_together={("admission", "internal_group_position")},
        ),
    ]
