# Generated by Django 3.2.16 on 2023-01-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="address",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="hometown",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="study",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
