# Generated by Django 3.2.16 on 2023-01-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0003_auto_20230103_2005"),
    ]

    operations = [
        migrations.AddField(
            model_name="interview",
            name="registered_at_samfundet",
            field=models.BooleanField(default=False),
        ),
    ]
