# Generated by Django 3.2.16 on 2023-01-20 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0005_auto_20230120_1550"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="interview_booking_late_batch_time",
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
    ]
