# Generated by Django 3.2.16 on 2023-01-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_admission_interview_booking_late_batch_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="admission",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
