# Generated by Django 3.2.5 on 2021-11-16 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0006_auto_20211116_0124"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="internalgrouppriority",
            options={
                "verbose_name": "Internal group priority",
                "verbose_name_plural": "Internal group priorities",
            },
        ),
    ]
