# Generated by Django 3.2.19 on 2023-07-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0007_admission_closed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewscheduletemplate",
            name="default_interview_notes",
            field=models.TextField(
                default="", help_text="Outlines questions to be used for each interview"
            ),
        ),
    ]
