# Generated by Django 3.2.11 on 2022-02-03 23:06

import admissions.models
import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organization", "0023_auto_20220130_2056"),
        ("admissions", "0008_applicant_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdmissionAvailableInternalGroupPositionData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "available_positions",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.admission",
                    ),
                ),
                (
                    "internal_group_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organization.internalgroupposition",
                    ),
                ),
            ],
            options={
                "unique_together": {("admission", "internal_group_position")},
            },
        ),
        migrations.CreateModel(
            name="ApplicantUnavailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_start", models.DateTimeField()),
                ("datetime_end", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="InternalGroupPositionPriority",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "applicant_priority",
                    models.CharField(
                        choices=[
                            ("first", "First"),
                            ("second", "Second"),
                            ("third", "Third"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "internal_group_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("want", "Want"),
                            ("do-not-want", "Do not want"),
                            ("reserve", "Reserve"),
                            ("should-be-admitted", "Should be admitted"),
                        ],
                        default="",
                        max_length=24,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal group position priority",
                "verbose_name_plural": "Internal group position priorities",
            },
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_start", models.DateTimeField()),
                ("interview_end", models.DateTimeField()),
                ("notes", models.TextField(blank=True, default="")),
                ("discussion", models.TextField(blank=True, default="")),
                (
                    "total_evaluation",
                    models.CharField(
                        choices=[
                            ("very-poor", "Very poor"),
                            ("poor", "Poor"),
                            ("medium", "Medium"),
                            ("good", "Good"),
                            ("very-good", "Very good"),
                        ],
                        default=None,
                        max_length=32,
                        null=True,
                    ),
                ),
                ("can_commit_three_semesters", models.BooleanField(default=True)),
                (
                    "cannot_commit_three_semesters_details",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewAdditionalEvaluationAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("very-little", "Very little"),
                            ("little", "Little"),
                            ("medium", "Medium"),
                            ("somewhat", "Somewhat"),
                            ("very", "Very"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.interview",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewAdditionalEvaluationStatement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewBooleanEvaluation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewBooleanEvaluationAnswer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.BooleanField()),
                (
                    "interview",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.interview",
                    ),
                ),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.interviewbooleanevaluation",
                    ),
                ),
            ],
            options={
                "unique_together": {("interview", "statement")},
            },
        ),
        migrations.CreateModel(
            name="InterviewLocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
                ("location_description", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="InterviewLocationAvailability",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_from", models.DateTimeField()),
                ("datetime_to", models.DateTimeField()),
                (
                    "interview_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability",
                        to="admissions.interviewlocation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterviewScheduleTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interview_period_start", models.DateTimeField()),
                ("interview_period_end", models.DateTimeField()),
                (
                    "default_interview_duration",
                    models.DurationField(default=datetime.timedelta(seconds=1800)),
                ),
                ("default_block_size", models.IntegerField(default=5)),
                (
                    "default_pause_duration",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="home_address",
            new_name="address",
        ),
        migrations.RenameField(
            model_name="applicant",
            old_name="town_address",
            new_name="hometown",
        ),
        migrations.AddField(
            model_name="applicant",
            name="token",
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="first_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=admissions.models.Applicant.image_dir
            ),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="last_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("email-sent", "Email sent"),
                    ("has-registered-profile", "Has registered profile"),
                    ("scheduled-interview", "Scheduled interview"),
                    ("interview-finished", "Interview finished"),
                    ("did-not-show-up-for-interview", "Did not show up for interview"),
                    ("to-be-called", "To be called"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("retracted-application", "Retracted application"),
                ],
                default="email-sent",
                max_length=64,
            ),
        ),
        migrations.DeleteModel(
            name="InternalGroupPriority",
        ),
        migrations.AddField(
            model_name="interviewadditionalevaluationanswer",
            name="statement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.interviewadditionalevaluationstatement",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="additional_evaluations",
            field=models.ManyToManyField(
                through="admissions.InterviewAdditionalEvaluationAnswer",
                to="admissions.InterviewAdditionalEvaluationStatement",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="boolean_evaluations",
            field=models.ManyToManyField(
                through="admissions.InterviewBooleanEvaluationAnswer",
                to="admissions.InterviewBooleanEvaluation",
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="interviewers",
            field=models.ManyToManyField(
                related_name="interviews_attended", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="interview",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.interviewlocation",
            ),
        ),
        migrations.AddField(
            model_name="internalgrouppositionpriority",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="priorities",
                to="admissions.applicant",
            ),
        ),
        migrations.AddField(
            model_name="internalgrouppositionpriority",
            name="internal_group_position",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="application_priorities",
                to="organization.internalgroupposition",
            ),
        ),
        migrations.AddField(
            model_name="applicantunavailability",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unavailability",
                to="admissions.applicant",
            ),
        ),
        migrations.AddField(
            model_name="admission",
            name="available_internal_group_positions",
            field=models.ManyToManyField(
                through="admissions.AdmissionAvailableInternalGroupPositionData",
                to="organization.InternalGroupPosition",
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="interview",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.interview",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="interviewadditionalevaluationanswer",
            unique_together={("interview", "statement")},
        ),
        migrations.AlterUniqueTogether(
            name="interview",
            unique_together={("interview_start", "interview_end", "location")},
        ),
        migrations.AlterUniqueTogether(
            name="internalgrouppositionpriority",
            unique_together={("applicant", "applicant_priority")},
        ),
    ]
