# Generated by Django 3.2.19 on 2023-07-05 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_auto_20230110_1123"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admissions", "0009_alter_admission_interview_booking_override_delta"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reasoning", models.TextField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="admissions.applicant",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendations",
                        to="organization.internalgroupposition",
                    ),
                ),
                (
                    "recommended_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Applicant recommendation",
                "verbose_name_plural": "Applicant recommendations",
            },
        ),
    ]
