# Generated by Django 3.2.11 on 2022-02-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0010_alter_internalgrouppositionpriority_internal_group_position",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewlocation",
            name="location_description",
            field=models.TextField(
                help_text="Tells the applicant details about the location. For example where to meet up before the interview.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interviewlocation",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="interviewscheduletemplate",
            name="default_block_size",
            field=models.IntegerField(
                default=5,
                help_text="Number of interviews happening back to back before a break",
            ),
        ),
    ]
