# Generated by Django 4.2.7 on 2025-07-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_alter_admissionavailableinternalgrouppositiondata_internal_group_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='booking_soft_wall_enabled',
            field=models.BooleanField(default=False, help_text="A booking soft wall enables 'hiding' available interviews after a certain timestamp. This is primarily used to force applicants to book an interview earlier in the admission period"),
        ),
        migrations.AddField(
            model_name='admission',
            name='booking_soft_wall_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
