# Generated by Django 3.2.11 on 2022-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0011_auto_20220203_2350"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialization", "Initialization"),
                    ("open", "Open"),
                    ("in-session", "In session"),
                    ("finalization", "Finalization"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
    ]
