# Generated by Django 3.2.12 on 2022-02-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0012_alter_admission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewadditionalevaluationstatement",
            name="statement",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="interviewbooleanevaluation",
            name="statement",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
