# Generated by Django 3.2.12 on 2022-02-17 13:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0013_auto_20220208_1232"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewscheduletemplate",
            name="interview_period_end",
        ),
        migrations.RemoveField(
            model_name="interviewscheduletemplate",
            name="interview_period_start",
        ),
        migrations.AddField(
            model_name="interviewscheduletemplate",
            name="default_interview_day_end",
            field=models.TimeField(default=datetime.time(20, 0)),
        ),
        migrations.AddField(
            model_name="interviewscheduletemplate",
            name="default_interview_day_start",
            field=models.TimeField(default=datetime.time(12, 0)),
        ),
        migrations.AddField(
            model_name="interviewscheduletemplate",
            name="interview_period_end_date",
            field=models.DateField(
                default=datetime.datetime(2022, 2, 17, 13, 45, 9, 437339, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="interviewscheduletemplate",
            name="interview_period_start_date",
            field=models.DateField(
                default=datetime.datetime(2022, 3, 3, 13, 45, 27, 976268, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
