# Generated by Django 3.2.12 on 2022-02-17 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0014_auto_20220217_1345"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewscheduletemplate",
            name="default_interview_day_end",
            field=models.TimeField(default=datetime.time(18, 0)),
        ),
    ]
