# Generated by Django 3.2.12 on 2022-02-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0015_alter_interviewscheduletemplate_default_interview_day_end",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="status",
            field=models.CharField(
                choices=[
                    ("initialization", "Initialization"),
                    ("interview-overview", "Interview overview"),
                    ("open", "Open"),
                    ("in-session", "In session"),
                    ("finalization", "Finalization"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
    ]
