# Generated by Django 3.2.12 on 2022-02-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_alter_admission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="date",
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
