# Generated by Django 3.2.12 on 2022-02-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_alter_admission_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="status",
            field=models.CharField(
                choices=[
                    ("configuration", "Configuration"),
                    ("interview-overview", "Interview overview"),
                    ("open", "Open"),
                    ("in-session", "In session"),
                    ("finalization", "Finalization"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
    ]
