# Generated by Django 3.2.12 on 2022-02-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0018_alter_admission_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewbooleanevaluation",
            name="order",
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
