# Generated by Django 3.2.12 on 2022-02-24 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0020_interviewadditionalevaluationstatement_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionavailableinternalgrouppositiondata",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_internal_group_posistions_data",
                to="admissions.admission",
            ),
        ),
        migrations.AlterField(
            model_name="admissionavailableinternalgrouppositiondata",
            name="available_positions",
            field=models.IntegerField(),
        ),
    ]
