# Generated by Django 3.2.12 on 2022-02-24 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0021_auto_20220224_2124"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionavailableinternalgrouppositiondata",
            name="admission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_internal_group_positions_data",
                to="admissions.admission",
            ),
        ),
    ]
