# Generated by Django 3.2.12 on 2022-02-25 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0022_alter_admissionavailableinternalgrouppositiondata_admission",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="interview",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant",
                to="admissions.interview",
            ),
        ),
    ]
