# Generated by Django 3.2.12 on 2022-02-27 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0023_alter_applicant_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="wants_digital_interview",
            field=models.BooleanField(default=False),
        ),
    ]
