# Generated by Django 3.2.12 on 2022-02-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0024_applicant_wants_digital_interview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="additional_evaluations",
            field=models.ManyToManyField(
                related_name="additional_evaluation_statement_answers",
                through="admissions.InterviewAdditionalEvaluationAnswer",
                to="admissions.InterviewAdditionalEvaluationStatement",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="boolean_evaluations",
            field=models.ManyToManyField(
                related_name="boolean_evaluation_answers",
                through="admissions.InterviewBooleanEvaluationAnswer",
                to="admissions.InterviewBooleanEvaluation",
            ),
        ),
    ]
