# Generated by Django 3.2.12 on 2022-02-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0025_auto_20220228_0253"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="additional_evaluations",
            field=models.ManyToManyField(
                through="admissions.InterviewAdditionalEvaluationAnswer",
                to="admissions.InterviewAdditionalEvaluationStatement",
            ),
        ),
        migrations.AlterField(
            model_name="interview",
            name="boolean_evaluations",
            field=models.ManyToManyField(
                through="admissions.InterviewBooleanEvaluationAnswer",
                to="admissions.InterviewBooleanEvaluation",
            ),
        ),
        migrations.AlterField(
            model_name="interviewadditionalevaluationanswer",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_evaluation_statement_answers",
                to="admissions.interview",
            ),
        ),
        migrations.AlterField(
            model_name="interviewbooleanevaluationanswer",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="boolean_evaluation_answers",
                to="admissions.interview",
            ),
        ),
    ]
