# Generated by Django 3.2.12 on 2022-02-28 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0026_auto_20220228_0302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="date",
            field=models.DateField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
