# Generated by Django 3.2.12 on 2022-03-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0028_auto_20220302_1926"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="will_be_admitted",
            field=models.BooleanField(default=False),
        ),
    ]
