# Generated by Django 3.2.12 on 2022-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0029_applicant_will_be_admitted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("email-sent", "Email sent"),
                    ("has-registered-profile", "Has registered profile"),
                    ("has-set-priorities", "Has set priorities"),
                    ("scheduled-interview", "Scheduled interview"),
                    ("interview-finished", "Interview finished"),
                    ("did-not-show-up-for-interview", "Did not show up for interview"),
                    ("to-be-called", "To be called"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("retracted-application", "Retracted application"),
                ],
                default="email-sent",
                max_length=64,
            ),
        ),
    ]
