# Generated by Django 3.2.12 on 2022-03-08 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0030_alter_applicant_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewadditionalevaluationanswer",
            name="interview",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="additional_evaluation_answers",
                to="admissions.interview",
            ),
        ),
    ]
