# Generated by Django 3.2.12 on 2022-03-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0031_alter_interviewadditionalevaluationanswer_interview"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="discussion_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="discussion_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="internalgrouppositionpriority",
            name="internal_group_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("want", "Want"),
                    ("do-not-want", "Do not want"),
                    ("reserve", "Reserve"),
                    ("should-be-admitted", "Should be admitted"),
                    ("pass-around", "Pass around"),
                ],
                default="",
                max_length=24,
                null=True,
            ),
        ),
    ]
