# Generated by Django 3.2.12 on 2022-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0032_auto_20220310_1517"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalgrouppositionpriority",
            name="internal_group_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("want", "Want"),
                    ("do-not-want", "Do not want"),
                    ("reserve", "Reserve"),
                    ("should-be-admitted", "Should be admitted"),
                    ("pass-around", "Pass around"),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
