# Generated by Django 3.2.12 on 2022-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0034_alter_admission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admission",
            name="status",
            field=models.CharField(
                choices=[
                    ("configuration", "Configuration"),
                    ("open", "Open"),
                    ("in-session", "In session"),
                    ("locked", "Locked"),
                    ("closed", "Closed"),
                ],
                default="open",
                max_length=32,
            ),
        ),
    ]
