# Generated by Django 3.2.12 on 2022-05-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0035_alter_admission_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewadditionalevaluationanswer",
            name="answer",
            field=models.CharField(
                blank=True,
                choices=[
                    ("very-little", "Very little"),
                    ("little", "Little"),
                    ("medium", "Medium"),
                    ("somewhat", "Somewhat"),
                    ("very", "Very"),
                ],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="interviewbooleanevaluationanswer",
            name="value",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
