# Generated by Django 3.2.12 on 2022-06-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0036_auto_20220530_1349"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interview",
            name="can_commit_three_semesters",
        ),
        migrations.RemoveField(
            model_name="interview",
            name="cannot_commit_three_semesters_details",
        ),
        migrations.AddField(
            model_name="applicant",
            name="can_commit_three_semesters",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="cannot_commit_three_semesters_details",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
