# Generated by Django 3.2.12 on 2022-06-06 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0037_auto_20220606_2000"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="open_for_other_positions",
            field=models.BooleanField(default=False),
        ),
    ]
