# Generated by Django 3.2.13 on 2022-06-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0039_alter_interview_total_evaluation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="internalgrouppositionpriority",
            name="internal_group_priority",
            field=models.CharField(
                blank=True,
                choices=[
                    ("want", "Want"),
                    ("do-not-want", "Do not want"),
                    ("reserve", "Reserve"),
                    ("currently-discussing", "Currently discussing"),
                    ("should-be-admitted", "Should be admitted"),
                    ("pass-around", "Pass around"),
                ],
                max_length=24,
                null=True,
            ),
        ),
    ]
