# Generated by Django 3.2.13 on 2022-06-22 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0027_internalgroup_group_icon"),
        ("admissions", "0042_applicantinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicantinterest",
            name="position_to_be_offered",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applicant_interest_offers",
                to="organization.internalgroupposition",
            ),
        ),
    ]
