# Generated by Django 3.2.13 on 2022-08-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "admissions",
            "0044_admissionavailableinternalgrouppositiondata_membership_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="admissionavailableinternalgrouppositiondata",
            name="membership_type",
            field=models.CharField(
                choices=[
                    ("functionary", "Functionary"),
                    ("active-functionary-pang", "Active functionary pang"),
                    ("old-functionary-pang", "Old functionary pang"),
                    ("gang-member", "Gang member"),
                    ("active-gang-member-pang", "Active gang member pang"),
                    ("old-gang-member-pang", "Old gang member pang"),
                    ("interest-group-member", "Interest group member"),
                    ("hangaround", "Hangaround"),
                    ("temporary-leave", "Temporary leave"),
                ],
                default="gang-member",
                max_length=32,
            ),
        ),
    ]
