# Generated by Django 3.2.13 on 2022-09-03 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "admissions",
            "0045_alter_admissionavailableinternalgrouppositiondata_membership_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="last_activity",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="last_notice",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="notice_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="applicant",
            name="notice_method",
            field=models.CharField(
                blank=True,
                choices=[("email", "Email"), ("call", "Call")],
                default=None,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="applicant",
            name="notice_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
