# Generated by Django 3.2.13 on 2022-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0046_auto_20220903_1522"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="notice_comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
