# Generated by Django 3.2.16 on 2022-11-02 12:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admissions", "0048_applicantcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interview",
            name="interviewers",
            field=models.ManyToManyField(
                blank=True,
                related_name="interviews_attended",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
