# Generated by Django 3.2.16 on 2022-11-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0049_alter_interview_interviewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="gdpr_consent",
            field=models.BooleanField(default=False),
        ),
    ]
