# Generated by Django 3.2.16 on 2022-11-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0050_applicant_gdpr_consent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicant",
            name="discussion_end",
        ),
        migrations.RemoveField(
            model_name="applicant",
            name="discussion_start",
        ),
        migrations.AlterField(
            model_name="applicant",
            name="status",
            field=models.CharField(
                choices=[
                    ("email-sent", "Email sent"),
                    ("has-registered-profile", "Has registered profile"),
                    ("has-set-priorities", "Has set priorities"),
                    ("scheduled-interview", "Scheduled interview"),
                    ("interview-finished", "Interview finished"),
                    ("did-not-show-up-for-interview", "Did not show up for interview"),
                    ("retracted-application", "Retracted application"),
                ],
                default="email-sent",
                max_length=64,
            ),
        ),
    ]
