# Generated by Django 3.2.16 on 2022-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0051_auto_20221103_1223"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicant",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="applicants"),
        ),
    ]
