# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 17:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CrossIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crossed', models.DateField()),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('person_crossing_in', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.CrossIn'),
        ),
        migrations.AddField(
            model_name='cross',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.Product'),
        ),
    ]
