# Generated by Django 3.2.16 on 2022-12-04 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("economy", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socisession",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sociordersessionorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_session_orders",
                to="economy.sociproduct",
            ),
        ),
        migrations.AddField(
            model_name="sociordersessionorder",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="economy.sociordersession",
            ),
        ),
        migrations.AddField(
            model_name="sociordersessionorder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soci_order_session_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sociordersession",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="soci_order_sessions_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sociordersession",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="soci_order_sessions_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sociordersession",
            name="invited_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="soci_order_sessions_invited_to",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socibankaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bank_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="economy.sociproduct"
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="session",
            field=models.ForeignKey(
                default=economy.models.SociSession.get_active_session,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="product_orders",
                to="economy.socisession",
            ),
        ),
        migrations.AddField(
            model_name="productorder",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_orders",
                to="economy.socibankaccount",
            ),
        ),
        migrations.AddField(
            model_name="depositcomment",
            name="deposit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="economy.deposit",
            ),
        ),
        migrations.AddField(
            model_name="depositcomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="all_deposit_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deposits",
                to="economy.socibankaccount",
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="verified_deposits",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
