# Generated by Django 2.2.7 on 2020-02-28 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socibankaccount',
            name='card_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
