# Generated by Django 3.2.18 on 2023-04-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0001_squashed_0007_alter_socisession_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="socisession",
            name="minimum_remaining_balance",
            field=models.IntegerField(
                default=0,
                help_text="Required remaining balance after placing a product order on a 'KRYSSELISTE'",
            ),
        ),
    ]
