# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0002_auto_20171114_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredCross',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_crossed', models.DateField()),
                ('date_registered', models.DateField(auto_now_add=True)),
                ('comment', models.CharField(max_length=100)),
                ('person_crossing_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='cross',
            name='cross_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.RegisteredCross'),
        ),
        migrations.AlterField(
            model_name='cross',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CrossIn',
        ),
    ]
