# Generated by Django 3.2.16 on 2023-02-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="resolved_amount",
            field=models.IntegerField(
                blank=True,
                help_text="Amount after deducting stripe fee's and flooring to a whole number",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="deposit",
            name="stripe_payment_id",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="deposit",
            name="stripe_payment_intent_status",
            field=models.CharField(
                blank=True,
                choices=[("CREATED", "Created"), ("SUCCESS", "Success")],
                default="CREATED",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="amount",
            field=models.IntegerField(help_text="Amount paid by customer"),
        ),
    ]
