# Generated by Django 3.2.16 on 2022-12-07 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productorder",
            options={
                "verbose_name": "Product order",
                "verbose_name_plural": "Product orders",
            },
        ),
        migrations.RemoveField(
            model_name="depositcomment",
            name="created",
        ),
        migrations.RemoveField(
            model_name="depositcomment",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="created",
        ),
        migrations.RemoveField(
            model_name="transfer",
            name="modified",
        ),
        migrations.AddField(
            model_name="depositcomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transfer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="productorder",
            index=models.Index(
                fields=["session", "source"], name="economy_pro_session_6d6c6d_idx"
            ),
        ),
    ]
