# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0002_auto_20180429_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='SociProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_number', models.CharField(max_length=50, unique=True, verbose_name='Product SKU number')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('description', models.TextField(blank=True, default=None, max_length=200, null=True)),
            ],
        ),
    ]
