# Generated by Django 3.2.16 on 2023-03-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0003_auto_20230209_1100"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="deposit_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("VIPPS", "Vipps"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("STRIPE", "Stripe"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="deposit",
            name="resolved_amount",
            field=models.IntegerField(
                blank=True,
                help_text="Amount after deducting stripe fee's and flooring to a whole number, if applicable.",
                null=True,
            ),
        ),
    ]
