# Generated by Django 4.2.3 on 2023-10-27 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0003_sociproduct_purchase_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductGhostOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghost_purchases",
                        to="economy.sociproduct",
                    ),
                ),
            ],
        ),
    ]
