# Generated by Django 3.1.2 on 2020-10-21 15:24

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_auto_20201021_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='session',
            field=models.ForeignKey(default=economy.models.SociSession.get_active_session, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_orders', to='economy.socisession'),
        ),
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
