# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('economy', '0003_auto_20171114_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='RegisteredCross',
            new_name='PurchaseList',
        ),
        migrations.RemoveField(
            model_name='cross',
            name='cross_in',
        ),
        migrations.RemoveField(
            model_name='cross',
            name='person',
        ),
        migrations.RemoveField(
            model_name='cross',
            name='product',
        ),
        migrations.RenameField(
            model_name='purchaselist',
            old_name='date_crossed',
            new_name='date_purchased',
        ),
        migrations.RenameField(
            model_name='purchaselist',
            old_name='person_crossing_in',
            new_name='signed_off_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Cross',
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='economy.PurchaseList'),
        ),
    ]
