# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_sociproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='receipt',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=economy.models.Deposit._receipt_upload_location),
        ),
        migrations.AddField(
            model_name='sociproduct',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.SociProduct'),
        ),
    ]
