# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-29 20:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0003_sociproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='economy.SociProduct'),
        ),
        migrations.AlterField(
            model_name='sociproduct',
            name='sku_number',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Product SKU number'),
        ),
    ]
