# Generated by Django 4.2.3 on 2023-11-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0004_productghostorder"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockMarketCrash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
