# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20171116_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to=economy.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='signed_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaselist',
            name='date_purchased',
            field=models.DateField(auto_now_add=True),
        ),
    ]
