# Generated by Django 3.1.2 on 2020-12-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20201021_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociproduct',
            name='icon',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
