# Generated by Django 3.1.2 on 2020-11-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20201021_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_orders', to='economy.socibankaccount'),
            preserve_default=False,
        ),
    ]
