# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-30 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20180429_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='economy.SociProduct'),
        ),
    ]
