# Generated by Django 3.2.18 on 2023-03-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0004_auto_20230303_1606"),
    ]

    operations = [
        migrations.AddField(
            model_name="socibankaccount",
            name="external_charge_secret",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
