# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0004_auto_20180930_1934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Transfer',
        ),
    ]
