# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-19 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_auto_20180430_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='receipt',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=economy.models.Deposit._receipt_upload_location),
        ),
        migrations.AddField(
            model_name='sociproduct',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
