# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_auto_20180930_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='product',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='signed_off_by',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='signed_off_time',
        ),
        migrations.AlterField(
            model_name='transfer',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_transfers', to='economy.SociBankAccount'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_transfers', to='economy.SociBankAccount'),
        ),
    ]
