# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_auto_20180222_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='signed_off_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
