# Generated by Django 3.1.2 on 2020-12-13 20:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0005_auto_20201213_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
