# Generated by Django 3.2.18 on 2023-03-06 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bar_tab", "0003_bartabcustomer_webhook_url"),
        ("economy", "0005_socibankaccount_external_charge_secret"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("webhook_attempts", models.IntegerField(default=0)),
                ("webhook_success", models.BooleanField(default=False)),
                (
                    "bank_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="external_charges",
                        to="economy.socibankaccount",
                    ),
                ),
                (
                    "bar_tab_customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_charges",
                        to="bar_tab.bartabcustomer",
                    ),
                ),
            ],
            options={
                "verbose_name": "External Charge",
                "verbose_name_plural": "External Charges",
            },
        ),
    ]
