# Generated by Django 3.1.6 on 2021-02-16 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0006_auto_20201205_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociproduct',
            name='icon',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
