# Generated by Django 5.2.17 on 2026-10-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0006_socirankedseason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociproduct",
            name="type",
            field=models.CharField(
                choices=[("FOOD", "Food"), ("DRINK", "Drink"), ("VOUCHER", "Voucher")],
                max_length=10,
                null=True,
            ),
        ),
    ]
