# Generated by Django 3.2.18 on 2023-04-18 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0007_alter_socisession_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="socisession",
            name="minimum_remaining_balance",
            field=models.IntegerField(
                default=0,
                help_text="The required remaining balance for an account after a purchase",
            ),
        ),
    ]
