# Generated by Django 3.2.5 on 2021-11-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0007_auto_20210216_2029"),
    ]

    operations = [
        migrations.AddField(
            model_name="productorder",
            name="purchased_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
