# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-30 21:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_period', models.DateTimeField(auto_now_add=True)),
                ('end_period', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='economy.PurchaseCollection'),
        ),
    ]
