# Generated by Django 3.1.7 on 2021-03-05 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0007_auto_20210216_2029'),
    ]

    operations = [
    ]
