# Generated by Django 5.2.17 on 2026-10-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0007_sociproduct_voucher_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="socisession",
            name="client_user_agent",
            field=models.CharField(
                blank=True,
                default="",
                help_text="User-Agent of the client that opened the session, for example 'X-App/2026.10.3 (ksg-kryssepc)'",
                max_length=255,
            ),
        ),
    ]
