# Generated by Django 3.1.7 on 2021-03-05 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0008_auto_20210305_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='ordered_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
