# Generated by Django 3.2.5 on 2021-12-02 13:47

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0008_productorder_purchased_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="signed_off_time",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="signed_off_by", null=True
            ),
        ),
    ]
