# Generated by Django 3.2.5 on 2021-12-02 22:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0009_alter_deposit_signed_off_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="created",
        ),
        migrations.RemoveField(
            model_name="deposit",
            name="modified",
        ),
        migrations.AddField(
            model_name="deposit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="deposit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
