# Generated by Django 2.1.2 on 2018-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0010_auto_20181007_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socibankaccount',
            name='balance',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
