# Generated by Django 3.2.5 on 2021-12-02 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0010_auto_20211202_2235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="signed_off_time",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
