# Generated by Django 3.2.5 on 2021-12-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0011_alter_deposit_signed_off_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
