# Generated by Django 2.1.2 on 2018-11-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0011_auto_20181112_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='comment',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
