# Generated by Django 2.1.2 on 2018-11-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0012_deposit_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
