# Generated by Django 3.2.12 on 2022-02-28 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0012_alter_deposit_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
