# Generated by Django 3.2.12 on 2022-02-28 18:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0013_alter_deposit_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="purchased_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
