# Generated by Django 2.1.5 on 2019-01-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0013_auto_20181124_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='comment',
            new_name='description',
        ),
    ]
