# Generated by Django 3.2.14 on 2022-10-12 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0015_productorder_cost"),
    ]

    operations = [
        migrations.RenameField(
            model_name="socisession",
            old_name="signed_off_by",
            new_name="created_by",
        ),
        migrations.AlterField(
            model_name="socisession",
            name="type",
            field=models.CharField(
                choices=[
                    ("SOCIETETEN", "Societeten"),
                    ("STILLETIME", "Stilletime"),
                    ("KRYSSELISTE", "Krysseliste"),
                ],
                default="SOCIETETEN",
                max_length=20,
            ),
        ),
    ]
