# Generated by Django 2.1.5 on 2019-01-29 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0015_depositcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socibankaccount',
            name='card_uuid',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
    ]
