# Generated by Django 3.2.14 on 2022-10-12 16:20

from django.db import migrations


class Migration(migrations.Migration):
    def delete_soci_sessions(apps, schema_editor):
        SociSession = apps.get_model("economy", "SociSession")
        ProductOrder = apps.get_model("economy", "ProductOrder")

        ProductOrder.objects.all().delete()
        SociSession.objects.all().delete()

    dependencies = [
        ("economy", "0016_auto_20221012_1611"),
    ]

    operations = [
        migrations.RunPython(delete_soci_sessions, migrations.RunPython.noop),
    ]
