# Generated by Django 2.1.5 on 2019-02-07 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0016_auto_20190129_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociproduct',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
