# Generated by Django 2.2 on 2019-04-22 16:27

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0017_sociproduct_valid_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositcomment',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='depositcomment',
            old_name='updated_at',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='deposit',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='depositcomment',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='depositcomment',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='signed_off_time',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='signed_off_by'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='signed_off_time',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='signed_off_by'),
        ),
        migrations.RenameField(
            model_name='purchasecollection',
            old_name='end_period',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='purchasecollection',
            old_name='start_period',
            new_name='start',
        ),
        migrations.RenameField(
            model_name='sociproduct',
            old_name='expiry_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='sociproduct',
            old_name='valid_from',
            new_name='start'
        ),
        migrations.AlterField(
            model_name='purchasecollection',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='purchasecollection',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
        migrations.AlterField(
            model_name='sociproduct',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='end'),
        ),
        migrations.AlterField(
            model_name='sociproduct',
            name='start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='start'),
        ),
    ]
