# Generated by Django 3.2.14 on 2022-10-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0018_auto_20221012_1835"),
    ]

    operations = [
        migrations.AddField(
            model_name="socisession",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
