# Generated by Django 2.2.7 on 2020-02-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0019_auto_20190427_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='socisession',
            name='closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socisession',
            name='type',
            field=models.CharField(choices=[('societeten', 'Societeten'), ('stilletime', 'Stilletime'), ('krysseliste', 'Krysseliste')], default='societeten', max_length=20),
        ),
    ]
