# Generated by Django 2.2.7 on 2020-02-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economy', '0020_socisession_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='socisession',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
