# Generated by Django 3.2.14 on 2022-10-12 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0020_remove_socisession_closed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="purchased_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
