# Generated by Django 3.2.14 on 2022-10-13 01:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0021_alter_productorder_purchased_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="socisession",
            name="creation_date",
            field=models.DateField(
                default=datetime.datetime(2022, 10, 13, 1, 13, 44, 654018, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
