# Generated by Django 3.2.14 on 2022-10-15 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0022_socisession_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociproduct",
            name="default_stilletime_product",
            field=models.BooleanField(default=False),
        ),
    ]
