# Generated by Django 3.2.14 on 2022-10-15 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0023_sociproduct_default_stilletime_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socisession",
            name="creation_date",
            field=models.DateField(default=datetime.date(2022, 10, 15)),
        ),
    ]
