# Generated by Django 3.2.14 on 2022-10-16 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0024_alter_socisession_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socisession",
            name="creation_date",
            field=models.DateField(default=datetime.date(2022, 10, 16)),
        ),
    ]
