# Generated by Django 3.2.16 on 2022-10-20 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0025_alter_socisession_creation_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociproduct",
            name="hide_from_api",
            field=models.BooleanField(
                default=datetime.datetime(2022, 10, 20, 13, 54, 12, 466589, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="socisession",
            name="creation_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
