# Generated by Django 3.2.16 on 2022-10-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0026_auto_20221020_1554"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sociproduct",
            name="hide_from_api",
            field=models.BooleanField(default=False),
        ),
    ]
