# Generated by Django 3.2.16 on 2022-10-25 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0028_alter_socisession_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productorder",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_orders",
                to="economy.socibankaccount",
            ),
        ),
    ]
