# Generated by Django 3.2.16 on 2022-10-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0029_alter_productorder_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociproduct",
            name="sg_id",
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
