# Generated by Django 3.2.16 on 2022-10-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0030_sociproduct_sg_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="deposit",
            name="migrated_from_sg",
            field=models.BooleanField(default=False),
        ),
    ]
