# Generated by Django 3.2.16 on 2022-11-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0033_deposit_approved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deposit",
            options={
                "permissions": (
                    ("approve_deposit", "Can approve deposits"),
                    ("invalidate_deposit", "Can invalidate deposits"),
                )
            },
        ),
    ]
