# Generated by Django 3.2.16 on 2022-11-18 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("economy", "0034_alter_deposit_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="SociOrderSession",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("FOOD_ORDERING", "Food Ordering"),
                            ("DRINK_ORDERING", "Drink Ordering"),
                            ("CLOSED", "Closed"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "order_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="soci_order_sessions"
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soci_order_sessions_closed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="soci_order_sessions_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="soci_order_sessions_invited_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soci Order Session",
                "verbose_name_plural": "Soci Order Sessions",
            },
        ),
        migrations.AddField(
            model_name="sociproduct",
            name="type",
            field=models.CharField(
                choices=[("FOOD", "Food"), ("DRINK", "Drink")], max_length=10, null=True
            ),
        ),
        migrations.CreateModel(
            name="SociOrderSessionOrder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_session_orders",
                        to="economy.sociproduct",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="economy.sociordersession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soci_order_session_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Soci Order Session Order",
                "verbose_name_plural": "Soci Order Session Orders",
            },
        ),
    ]
