# Generated by Django 3.2.16 on 2022-11-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0035_auto_20221118_2302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socisession",
            name="type",
            field=models.CharField(
                choices=[
                    ("SOCIETETEN", "Societeten"),
                    ("STILLETIME", "Stilletime"),
                    ("KRYSSELISTE", "Krysseliste"),
                    ("BURGERLISTE", "Burgerliste"),
                ],
                default="SOCIETETEN",
                max_length=20,
            ),
        ),
    ]
