# Generated by Django 3.2.16 on 2022-11-21 12:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("economy", "0036_alter_socisession_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="sociordersessionorder",
            name="ordered_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2022, 11, 21, 12, 2, 32, 467254, tzinfo=utc),
            ),
            preserve_default=False,
        ),
    ]
