MEASUREMENT_TYPE_TEMPERATURE = 'temperature'
MEASUREMENT_TYPE_HUMIDITY = 'humidity'
MEASUREMENT_TYPE_SOUND = 'sound'

MEASUREMENT_TYPE_CHOICES = (
    (MEASUREMENT_TYPE_TEMPERATURE, 'Temperature'),
    (MEASUREMENT_TYPE_HUMIDITY, 'Humidity'),
    (MEASUREMENT_TYPE_SOUND, 'Sound'),
)
