default_user_types = [
    {
        "name": "Administrator",
        "description": "En administrator har full tilgang utenom administrering av opptak",
        "requires_superuser": False,
        "requires_self": True,
        "permissions": [
            "users.add_user",
            "users.change_user",
            "users.delete_user",
            "users.view_user",
            "users.change_usertype",
            "users.view_usertype",
            "quotes.change_quote",
            "quotes.delete_quote",
        ],
    },
    {
        "name": "Funksjonær",
        "description": "En funksjonær har tilgang intervjusystemet og oprretting/redigering av referater",
        "requires_superuser": False,
        "requires_self": False,
        "permissions": [],
    },
    {
        "name": "Personalansvarlig",
        "description": "En personalansvarlig har tilgang til å endre på personalopplysninger, og underkjenne sitater",
        "requires_superuser": False,
        "requires_self": False,
        "permissions": [],
    },
    {
        "name": "Økonomiansvarlig",
        "description": "En økonomiansvarlig har tilgang til BSF modulen og moderering av innskudd",
        "requires_superuser": False,
        "requires_self": True,
        "permissions": [],
    },
    {
        "name": "Opptaksadministrator",
        "requires_superuser": True,
        "requires_self": False,
        "permissions": [],
    },
    {
        "name": "Velferdsansvarlig",
        "requires_superuser": False,
        "requires_self": False,
        "permissions": [],
    },
    {
        "name": "Intervjuer",
        "description": "En intervjuer har tilgang til intervjumodulen, brukes for å gi tilgang til opptaket om man"
        "trenger hjelp med å holde intervjuer",
        "requires_superuser": False,
        "requires_self": False,
        "permissions": [],
    },
]

default_allergies = [
    "Laktose",
    "Gluten",
    "Melk",
    "Egg",
    "Sopp",
    "Nøtter: tåler spor",
    "Nøtter: literally dør",
    "Malt",
    "Scampi",
    "Kamskjell",
    "Appelsin",
    "Pecannøtter",
    "Mango",
    "Sitrus",
    "Rå epler",
    "Rå gulrøtter",
    "Rå fennikel",
    "Rå edamamebønner",
    "Sukkererter",
    "Kokos",
    "Avokado",
    "Solsikkekjerner",
    "Hasselnøtter",
    "Valnøtter",
    "Eple",
]
