# Generated by Django 3.2.18 on 2023-04-28 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InternalControlDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InternalControlDocumentItemCollectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="InternalControlDocumentTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="InternalControlDocumentTemplateItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "internal_control_document_item_collection_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_items",
                        to="internalcontrol.internalcontroldocumentitemcollectiontemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Control Document Template Item",
                "verbose_name_plural": "Internal Control Document Template Items",
            },
        ),
        migrations.AddField(
            model_name="internalcontroldocumentitemcollectiontemplate",
            name="internal_control_document_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_item_collections",
                to="internalcontrol.internalcontroldocumenttemplate",
            ),
        ),
        migrations.CreateModel(
            name="InternalControlDocumentItemCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("order", models.IntegerField()),
                (
                    "internal_control_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_collections",
                        to="internalcontrol.internalcontroldocument",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InternalControlDocumentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("order", models.IntegerField()),
                (
                    "done_by",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_control_document_items_done",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "internal_control_document_item_collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="internalcontrol.internalcontroldocumentitemcollection",
                    ),
                ),
            ],
            options={
                "verbose_name": "Internal Control Document Item",
                "verbose_name_plural": "Internal Control Document Items",
            },
        ),
        migrations.AddField(
            model_name="internalcontroldocument",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="generated_documents",
                to="internalcontrol.internalcontroldocumenttemplate",
            ),
        ),
    ]
