# Generated by Django 3.2.18 on 2023-04-29 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("internalcontrol", "0002_auto_20230429_1525"),
    ]

    operations = [
        migrations.AddField(
            model_name="internalcontroldocumenttemplateitem",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BARISTA", "Barista"),
                    ("KAFEANSVARLIG", "Kaféansvarlig"),
                    ("BARSERVITOR", "Barservitør"),
                    ("HOVMESTER", "Hovmester"),
                    ("KOKK", "Kokk"),
                    ("SOUSCHEF", "Souschef"),
                    ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                    ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                    ("BRYGGER", "Brygger"),
                    ("BARTENDER", "Bartender"),
                    ("BARSJEF", "Barsjef"),
                    ("SPRITBARTENDER", "Spritbartender"),
                    ("SPRITBARSJEF", "Spritbarsjef"),
                    ("UGLE", "Ugle"),
                    ("BRANNVAKT", "Brannvakt"),
                    ("RYDDEVAKT", "Ryddevakt"),
                    ("BAEREVAKT", "Bærevakt"),
                    ("SOCIVAKT", "Socivakt"),
                ],
                default=None,
                help_text="Imposes a restriction on what role a user has to have on a shift in order to mark this item as done",
                max_length=255,
                null=True,
            ),
        ),
    ]
