# Generated by Django 3.1.2 on 2020-11-19 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20201119_1723'),
        ('commissions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
