# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'schedules',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'schedule slot types',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'schedule templates',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'shifts',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Shift slots',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotDayRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(choices=[('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday'), ('wk', 'Weekdays'), ('ed', 'Weekends'), ('fu', 'Full weekends')], max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Shift slot day rules',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meet_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'shift slot groups',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotGroupInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Shift slot group interest',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotGroupTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meet_time', models.TimeField()),
                ('start_time', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'shift slot group templates',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
            options={
                'verbose_name_plural': 'Shift slot templates',
            },
        ),
        migrations.CreateModel(
            name='ShiftTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Shift trade',
            },
        ),
        migrations.CreateModel(
            name='ShiftTradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Shift trade offer',
            },
        ),
    ]
