# Generated by Django 3.2.16 on 2022-12-04 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttrade",
            name="offeror",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_trades_offered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shifttrade",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="schedules.shift",
            ),
        ),
        migrations.AddField(
            model_name="shifttrade",
            name="taker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_trades_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shifttrade",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="schedule_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_templates",
                to="schedules.scheduletemplate",
            ),
        ),
        migrations.AddField(
            model_name="shiftslottemplate",
            name="shift_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_slot_templates",
                to="schedules.shifttemplate",
            ),
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slots",
                to="schedules.shift",
            ),
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filled_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="generated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts_generated",
                to="schedules.scheduletemplate",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="schedules.schedule",
            ),
        ),
        migrations.AddField(
            model_name="scheduletemplate",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schedules.schedule"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shiftslottemplate",
            unique_together={("shift_template", "role")},
        ),
        migrations.AlterUniqueTogether(
            name="scheduletemplate",
            unique_together={("name", "schedule")},
        ),
    ]
