# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_auto_20180125_2044'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shifttradeoffer',
            name='offeror',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttradeoffer',
            name='shift_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_to_shifts', to='schedules.Shift'),
        ),
        migrations.AddField(
            model_name='shifttradeoffer',
            name='shift_trade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='schedules.ShiftTrade'),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='offeror',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_offered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='shift_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_trades', to='schedules.Shift'),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='shift_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_in_trades', to='schedules.Shift'),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_trades_signed_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftslottemplate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ShiftSlotGroupTemplate'),
        ),
        migrations.AddField(
            model_name='shiftslottemplate',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleSlotType'),
        ),
        migrations.AddField(
            model_name='shiftslotgrouptemplate',
            name='schedule_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleTemplate'),
        ),
        migrations.AddField(
            model_name='shiftslotgroupinterest',
            name='shift_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ShiftSlotGroup'),
        ),
        migrations.AddField(
            model_name='shiftslotgroupinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftslotgroup',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule'),
        ),
        migrations.AddField(
            model_name='shiftslotdayrule',
            name='shift_slot_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rules', to='schedules.ShiftSlotGroupTemplate'),
        ),
        migrations.AddField(
            model_name='shiftslot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ShiftSlotGroup'),
        ),
        migrations.AddField(
            model_name='shiftslot',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ScheduleSlotType'),
        ),
        migrations.AddField(
            model_name='shift',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='filled_shift', to='schedules.ShiftSlot'),
        ),
        migrations.AddField(
            model_name='shift',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduletemplate',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule'),
        ),
        migrations.AddField(
            model_name='scheduleslottype',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.Schedule'),
        ),
        migrations.AddField(
            model_name='scheduleslottype',
            name='standard_groups',
            field=models.ManyToManyField(blank=True, to='organization.InternalGroup'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftslotgroupinterest',
            unique_together=set([('shift_group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='shiftslotgroup',
            unique_together=set([('name', 'schedule')]),
        ),
        migrations.AlterUniqueTogether(
            name='shiftslotdayrule',
            unique_together=set([('rule', 'shift_slot_template')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together=set([('name', 'schedule')]),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleslottype',
            unique_together=set([('name', 'schedule')]),
        ),
    ]
