# Generated by Django 3.2.16 on 2023-01-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("RUNDHALLEN", "Rundhallen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                    ("KONTORET", "Kontoret"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("RUNDHALLEN", "Rundhallen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                    ("KONTORET", "Kontoret"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
