# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0002_auto_20171117_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftTrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offeror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_offered', to=settings.AUTH_USER_MODEL)),
                ('shift_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_trades', to='schedules.Shift')),
                ('shift_taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taken_in_trades', to='schedules.Shift')),
                ('signed_off_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_trades_signed_off', to=settings.AUTH_USER_MODEL)),
                ('taker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shifts_taken', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('offeror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_offers', to=settings.AUTH_USER_MODEL)),
                ('shift_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_to_shifts', to='schedules.Shift')),
                ('shift_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='schedules.ShiftTrade')),
            ],
        ),
    ]
