# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_shifttrade_shifttradeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftslotgroup',
            name='meet_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 8, 46, 34, 94797, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftslotgroup',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 17, 8, 46, 42, 918758, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftslot',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shiftslot',
            name='start',
            field=models.TimeField(),
        ),
    ]
