# Generated by Django 3.2.16 on 2023-01-27 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0003_shiftinterest"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="default_role",
            field=models.CharField(
                choices=[
                    ("BARISTA", "Barista"),
                    ("KAFEANSVARLIG", "Kaféansvarlig"),
                    ("BARSERVITOR", "Barservitør"),
                    ("HOVMESTER", "Hovmester"),
                    ("KOKK", "Kokk"),
                    ("SOUSCHEF", "Souschef"),
                    ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                    ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                    ("BRYGGER", "Brygger"),
                    ("BARTENDER", "Bartender"),
                    ("BARSJEF", "Barsjef"),
                    ("SPRITBARTENDER", "Spritbartender"),
                    ("SPRITBARSJEF", "Spritbarsjef"),
                    ("UGLE", "Ugle"),
                    ("BRANNVAKT", "Brannvakt"),
                    ("RYDDEVAKT", "Ryddevakt"),
                    ("BAEREVAKT", "Bærevakt"),
                    ("SOCIVAKT", "Socivakt"),
                ],
                default=None,
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shiftinterest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ScheduleRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "autofill_as",
                    models.CharField(
                        choices=[
                            ("BARISTA", "Barista"),
                            ("KAFEANSVARLIG", "Kaféansvarlig"),
                            ("BARSERVITOR", "Barservitør"),
                            ("HOVMESTER", "Hovmester"),
                            ("KOKK", "Kokk"),
                            ("SOUSCHEF", "Souschef"),
                            ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                            ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                            ("BRYGGER", "Brygger"),
                            ("BARTENDER", "Bartender"),
                            ("BARSJEF", "Barsjef"),
                            ("SPRITBARTENDER", "Spritbartender"),
                            ("SPRITBARSJEF", "Spritbarsjef"),
                            ("UGLE", "Ugle"),
                            ("BRANNVAKT", "Brannvakt"),
                            ("RYDDEVAKT", "Ryddevakt"),
                            ("BAEREVAKT", "Bærevakt"),
                            ("SOCIVAKT", "Socivakt"),
                        ],
                        default=None,
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.schedule",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
