# Generated by Django 3.2.16 on 2023-02-16 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20230127_1623'),
        ('schedules', '0003_auto_20230129_1659'),
    ]

    operations = [
    ]
