# Generated by Django 3.2.16 on 2023-03-02 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0003_auto_20230127_1623"),
        ("schedules", "0004_auto_20230127_1655"),
    ]

    operations = []
