# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20171117_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftslotgrouptemplate',
            name='meet_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 17, 8, 49, 57, 120301, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shiftslotgrouptemplate',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2017, 11, 17, 8, 50, 4, 160329, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shiftslottemplate',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shiftslottemplate',
            name='start',
            field=models.TimeField(),
        ),
    ]
