# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0005_auto_20171117_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftSlotGroupInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.ShiftSlotGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
