# Generated by Django 3.2.18 on 2023-03-15 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0005_merge_0003_auto_20230127_1623_0004_auto_20230127_1655"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleroster",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roster",
                to="schedules.schedule",
            ),
        ),
        migrations.AlterField(
            model_name="scheduleroster",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosters",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("RUNDHALLEN", "Rundhallen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("RUNDHALLEN", "Rundhallen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
