# Generated by Django 3.2.18 on 2023-04-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("internalcontrol", "0002_auto_20230429_1525"),
        ("schedules", "0007_auto_20230426_2317"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="internal_control_document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts",
                to="internalcontrol.internalcontroldocument",
            ),
        ),
        migrations.AddField(
            model_name="shifttemplate",
            name="internal_control_document_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_templates",
                to="internalcontrol.internalcontroldocumenttemplate",
            ),
        ),
    ]
