# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 19:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_auto_20180208_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifttrade',
            name='shift_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_in_trades', to='schedules.Shift'),
        ),
        migrations.AlterField(
            model_name='shifttrade',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_trades_signed_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shifttrade',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_taken', to=settings.AUTH_USER_MODEL),
        ),
    ]
