# Generated by Django 4.2.7 on 2025-02-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_shift_location_alter_shifttemplate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinterest',
            name='interest_type',
            field=models.CharField(choices=[('interested', 'Interested'), ('available', 'Available'), ('unavailable', 'Unavailable')], default='interested', max_length=12),
        ),
    ]
