# Generated by Django 2.2 on 2019-04-22 16:27

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20180208_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftslotdayrule',
            name='rule',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='mo', max_length=2, no_check_for_status=True),
        ),
    ]
