# Generated by Django 4.2.7 on 2025-02-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_shiftinterest_interest_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftinterest',
            name='note',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
