# Generated by Django 5.2.17 on 2026-10-05 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_auto_20230110_1123"),
        ("schedules", "0010_schedule_internal_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduleroster",
            name="added_manually",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheduleroster",
            name="count_from",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduleroster",
            name="default_availability",
            field=models.CharField(
                choices=[("available", "Available"), ("opt_in", "Opt in")],
                default="available",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="scheduleroster",
            name="manually_edited",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="scheduleroster",
            name="shift_cap",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ScheduleRosterGrouping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("functionary", "Functionary"),
                            ("active-functionary-pang", "Active functionary pang"),
                            ("old-functionary-pang", "Old functionary pang"),
                            ("gang-member", "Gang member"),
                            ("active-gang-member-pang", "Active gang member pang"),
                            ("old-gang-member-pang", "Old gang member pang"),
                            ("interest-group-member", "Interest group member"),
                            ("hangaround", "Hangaround"),
                            ("temporary-leave", "Temporary leave"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("BARISTA", "Barista"),
                            ("KAFEANSVARLIG", "Kaféansvarlig"),
                            ("BARSERVITOR", "Barservitør"),
                            ("HOVMESTER", "Hovmester"),
                            ("KOKK", "Kokk"),
                            ("SOUSCHEF", "Souschef"),
                            ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                            ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                            ("BRYGGER", "Brygger"),
                            ("BARTENDER", "Bartender"),
                            ("BARSJEF", "Barsjef"),
                            ("SPRITBARTENDER", "Spritbartender"),
                            ("SPRITBARSJEF", "Spritbarsjef"),
                            ("UGLE", "Ugle"),
                            ("BRANNVAKT", "Brannvakt"),
                            ("RYDDEVAKT", "Ryddevakt"),
                            ("BAEREVAKT", "Bærevakt"),
                            ("SOCIVAKT", "Socivakt"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "default_availability",
                    models.CharField(
                        choices=[("available", "Available"), ("opt_in", "Opt in")],
                        max_length=12,
                    ),
                ),
                ("shift_cap", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "internal_group_position",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="organization.internalgroupposition",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_groupings",
                        to="schedules.schedule",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scheduleroster",
            name="grouping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="roster_entries",
                to="schedules.schedulerostergrouping",
            ),
        ),
        migrations.AddConstraint(
            model_name="schedulerostergrouping",
            constraint=models.UniqueConstraint(
                fields=("schedule", "internal_group_position", "position_type"),
                name="unique_roster_grouping",
            ),
        ),
    ]
