# Generated by Django 3.2 on 2021-04-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0010_auto_20210408_1155"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslotgroupinterest",
            name="shift_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interests",
                to="schedules.shiftslotgroup",
            ),
        ),
    ]
