# Generated by Django 4.2.7 on 2025-03-04 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20230110_1123'),
        ('schedules', '0011_alter_shift_location_alter_shifttemplate_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleRosterGrouping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BARISTA', 'Barista'), ('KAFEANSVARLIG', 'Kaféansvarlig'), ('BARSERVITOR', 'Barservitør'), ('HOVMESTER', 'Hovmester'), ('KOKK', 'Kokk'), ('SOUSCHEF', 'Souschef'), ('ARRANGEMENTBARTENDER', 'Arrangementbartender'), ('ARRANGEMENTANSVARLIG', 'Arrangementansvarlig'), ('BRYGGER', 'Brygger'), ('BARTENDER', 'Bartender'), ('BARSJEF', 'Barsjef'), ('SPRITBARTENDER', 'Spritbartender'), ('SPRITBARSJEF', 'Spritbarsjef'), ('UGLE', 'Ugle'), ('BRANNVAKT', 'Brannvakt'), ('RYDDEVAKT', 'Ryddevakt'), ('BAEREVAKT', 'Bærevakt'), ('SOCIVAKT', 'Socivakt')], max_length=24)),
                ('position_type', models.CharField(choices=[('functionary', 'Functionary'), ('active-functionary-pang', 'Active functionary pang'), ('old-functionary-pang', 'Old functionary pang'), ('gang-member', 'Gang member'), ('active-gang-member-pang', 'Active gang member pang'), ('old-gang-member-pang', 'Old gang member pang'), ('interest-group-member', 'Interest group member'), ('hangaround', 'Hangaround'), ('temporary-leave', 'Temporary leave')], max_length=24)),
                ('default_availability', models.CharField(choices=[('interested', 'Interested'), ('available', 'Available'), ('unavailable', 'Unavailable')], max_length=12)),
                ('internal_group_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.internalgroupposition')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
            ],
            options={
                'verbose_name_plural': 'Schedule roster groupings',
            },
        ),
    ]
