# Generated by Django 3.2.12 on 2022-03-13 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0011_alter_shiftslotgroupinterest_shift_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69, unique=True)),
                ('description', models.TextField(null=True)),
                ('location', models.CharField(choices=[('LYCHE', 'Lyche'), ('EDGAR', 'Edgar'), ('BODEGA', 'Bodega')], max_length=69)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('attendance_time', models.TimeField()),
                ('required_shifts', models.JSONField(default=dict)),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[(1, 'KAFEANSVARLIG'), (2, 'SPRITSJEF'), (3, 'BARISTA'), (4, 'BARTENDER')], max_length=69)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_by', to='schedules.newshift')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
