# Generated by Django 3.2.12 on 2022-03-15 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_auto_20220130_2056'),
        ('schedules', '0012_newshift_usershift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usershift',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_role', to='organization.internalgroupposition'),
        ),
    ]
