# Generated by Django 5.2.17 on 2026-10-05 14:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0012_clean_schedule_roster"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="scheduleroster",
            name="autofill_as",
            field=models.CharField(
                choices=[
                    ("BARISTA", "Barista"),
                    ("KAFEANSVARLIG", "Kaféansvarlig"),
                    ("BARSERVITOR", "Barservitør"),
                    ("HOVMESTER", "Hovmester"),
                    ("KOKK", "Kokk"),
                    ("SOUSCHEF", "Souschef"),
                    ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                    ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                    ("BRYGGER", "Brygger"),
                    ("BARTENDER", "Bartender"),
                    ("BARSJEF", "Barsjef"),
                    ("SPRITBARTENDER", "Spritbartender"),
                    ("SPRITBARSJEF", "Spritbarsjef"),
                    ("UGLE", "Ugle"),
                    ("BRANNVAKT", "Brannvakt"),
                    ("RYDDEVAKT", "Ryddevakt"),
                    ("BAEREVAKT", "Bærevakt"),
                    ("SOCIVAKT", "Socivakt"),
                ],
                max_length=64,
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduleroster",
            constraint=models.UniqueConstraint(
                fields=("schedule", "user"), name="unique_schedule_roster_user"
            ),
        ),
    ]
