# Generated by Django 4.2.7 on 2026-10-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_schedulerostergrouping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAutofillAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='shiftslot',
            name='autofilled_by',
            field=models.ForeignKey(blank=True, default=None, help_text='Identifier to group together', null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduleautofillaction'),
        ),
    ]
