# Generated by Django 5.2.17 on 2026-10-05 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0013_schedule_roster_constraints"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shiftinterest",
            name="note",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="shiftinterest",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("unavailability", "Unavailability")],
                default="manual",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="shiftinterest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="PlanningPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_from", models.DateField()),
                ("date_to", models.DateField()),
                ("deadline", models.DateTimeField()),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_periods",
                        to="schedules.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_from"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("date_to__gte", models.F("date_from"))),
                        name="planning_period_dates_in_order",
                    )
                ],
            },
        ),
    ]
