# Generated by Django 3.2.12 on 2022-03-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_remove_newshift_contact_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newshift',
            old_name='required_shifts',
            new_name='required_roles',
        ),
    ]
