# Generated by Django 5.2.17 on 2026-10-05 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0015_dedupe_shift_interest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shiftinterest",
            constraint=models.UniqueConstraint(
                fields=("shift", "user"), name="unique_shift_interest_user"
            ),
        ),
    ]
