# Generated by Django 3.2.12 on 2022-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_rename_required_shifts_newshift_required_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newshift',
            name='required_roles',
            field=models.JSONField(default=[]),
        ),
    ]
