# Generated by Django 3.2.12 on 2022-03-20 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0016_alter_newshift_required_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newshift',
            name='location',
        ),
        migrations.AddField(
            model_name='newshift',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule'),
        ),
    ]
