# Generated by Django 3.2.12 on 2022-03-22 18:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0017_auto_20220320_1920'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduletemplate',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='scheduletemplate',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='shiftslot',
            name='group',
        ),
        migrations.RemoveField(
            model_name='shiftslot',
            name='type',
        ),
        migrations.AlterUniqueTogether(
            name='shiftslotgroupdayrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shiftslotgroupdayrule',
            name='shift_slot_group_template',
        ),
        migrations.AlterUniqueTogether(
            name='shiftslotgroupinterest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='shiftslotgroupinterest',
            name='shift_group',
        ),
        migrations.RemoveField(
            model_name='shiftslotgroupinterest',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shiftslotgrouptemplate',
            name='schedule_template',
        ),
        migrations.RemoveField(
            model_name='shiftslottemplate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='shiftslottemplate',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shifttradeoffer',
            name='offeror',
        ),
        migrations.RemoveField(
            model_name='shifttradeoffer',
            name='shift_offer',
        ),
        migrations.RemoveField(
            model_name='shifttradeoffer',
            name='shift_trade',
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shifttrade',
            options={},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='offeror',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='shift_offer',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='shift_taker',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='signed_off_by',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='taker',
        ),
        migrations.AddField(
            model_name='shift',
            name='attendance_time',
            field=models.TimeField(default=datetime.time(15, 0)),
        ),
        migrations.AddField(
            model_name='shift',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=69, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='required_roles',
            field=models.JSONField(default=[]),
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.schedule'),
        ),
        migrations.AddField(
            model_name='shift',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='shift',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='schedules.usershift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='status',
            field=models.CharField(choices=[('Offered', 'Offered'), ('Requested', 'Requested'), ('Verified', 'Verified')], default='Offered', max_length=69),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='verified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usershift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filled_by', to='schedules.shift'),
        ),
        migrations.DeleteModel(
            name='NewShift',
        ),
        migrations.DeleteModel(
            name='ScheduleTemplate',
        ),
        migrations.DeleteModel(
            name='ShiftSlot',
        ),
        migrations.DeleteModel(
            name='ShiftSlotGroupDayRule',
        ),
        migrations.DeleteModel(
            name='ShiftSlotGroupInterest',
        ),
        migrations.DeleteModel(
            name='ShiftSlotGroupTemplate',
        ),
        migrations.DeleteModel(
            name='ShiftSlotTemplate',
        ),
        migrations.DeleteModel(
            name='ShiftTradeOffer',
        ),
    ]
