# Generated by Django 3.2.12 on 2022-03-22 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0023_auto_20220130_2056'),
        ('schedules', '0018_auto_20220322_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.schedule')),
            ],
            options={
                'verbose_name_plural': 'schedule templates',
                'unique_together': {('name', 'schedule')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotGroupTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meet_time', models.TimeField()),
                ('start_time', models.TimeField()),
                ('schedule_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduletemplate')),
            ],
            options={
                'verbose_name_plural': 'shift slot group templates',
            },
        ),
        migrations.AlterModelOptions(
            name='shifttrade',
            options={'verbose_name_plural': 'Shift trade'},
        ),
        migrations.RemoveField(
            model_name='shift',
            name='required_roles',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='status',
        ),
        migrations.RemoveField(
            model_name='shifttrade',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='shift',
            name='contact_person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='required_shifts',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='offeror',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shifts_offered', to='users.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='shift_offer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='offered_in_trades', to='schedules.shift'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='shift_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_in_trades', to='schedules.shift'),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='signed_off_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_trades_signed_off', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shifttrade',
            name='taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shifts_taken', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='shift',
            name='attendance_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='usershift',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.internalgroupposition'),
        ),
        migrations.CreateModel(
            name='ShiftTradeOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('offeror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_offers', to=settings.AUTH_USER_MODEL)),
                ('shift_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offered_to_shifts', to='schedules.shift')),
                ('shift_trade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_offers', to='schedules.shifttrade')),
            ],
            options={
                'verbose_name_plural': 'Shift trade offer',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.shiftslotgrouptemplate')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduleslottype')),
            ],
            options={
                'verbose_name_plural': 'Shift slot templates',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_slots', to='schedules.shiftslotgroup')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedules.scheduleslottype')),
            ],
            options={
                'verbose_name_plural': 'Shift slots',
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotGroupInterest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='schedules.shiftslotgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shift slot group interest',
                'unique_together': {('shift_group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ShiftSlotGroupDayRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', model_utils.fields.StatusField(choices=[('mo', 'Monday'), ('tu', 'Tuesday'), ('we', 'Wednesday'), ('th', 'Thursday'), ('fr', 'Friday'), ('sa', 'Saturday'), ('su', 'Sunday'), ('wk', 'Weekdays'), ('ed', 'Weekends'), ('fu', 'Full weekends')], default='mo', max_length=2, no_check_for_status=True)),
                ('shift_slot_group_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_rules', to='schedules.shiftslotgrouptemplate')),
            ],
            options={
                'verbose_name_plural': 'Shift slot group day rules',
                'unique_together': {('rule', 'shift_slot_group_template')},
            },
        ),
    ]
