# Generated by Django 5.2.17 on 2026-10-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0019_autofill_run"),
    ]

    operations = [
        migrations.AddField(
            model_name="planningperiod",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
