# Generated by Django 3.2.13 on 2022-09-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0021_rename_contact_person_shift_created_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shift",
            options={"verbose_name_plural": "shifts"},
        ),
        migrations.RemoveField(
            model_name="shift",
            name="description",
        ),
        migrations.RemoveField(
            model_name="shift",
            name="required_shifts",
        ),
        migrations.AddField(
            model_name="schedule",
            name="single_venue",
            field=models.BooleanField(default=False),
        ),
    ]
