# Generated by Django 3.2.13 on 2022-09-12 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("schedules", "0022_auto_20220911_1949"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shiftslotgroupdayrule",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shiftslotgroupdayrule",
            name="shift_slot_group_template",
        ),
        migrations.AlterUniqueTogether(
            name="shiftslotgroupinterest",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="shiftslotgroupinterest",
            name="shift_group",
        ),
        migrations.RemoveField(
            model_name="shiftslotgroupinterest",
            name="user",
        ),
        migrations.RemoveField(
            model_name="shiftslottemplate",
            name="group",
        ),
        migrations.RemoveField(
            model_name="shiftslottemplate",
            name="type",
        ),
        migrations.RemoveField(
            model_name="shifttradeoffer",
            name="offeror",
        ),
        migrations.RemoveField(
            model_name="shifttradeoffer",
            name="shift_offer",
        ),
        migrations.RemoveField(
            model_name="shifttradeoffer",
            name="shift_trade",
        ),
        migrations.RemoveField(
            model_name="usershift",
            name="role",
        ),
        migrations.RemoveField(
            model_name="usershift",
            name="shift",
        ),
        migrations.RemoveField(
            model_name="usershift",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="shiftslot",
            options={},
        ),
        migrations.AlterModelOptions(
            name="shifttrade",
            options={},
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="end",
            new_name="datetime_end",
        ),
        migrations.RenameField(
            model_name="shift",
            old_name="start",
            new_name="datetime_start",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="single_venue",
        ),
        migrations.RemoveField(
            model_name="shiftslot",
            name="end",
        ),
        migrations.RemoveField(
            model_name="shiftslot",
            name="group",
        ),
        migrations.RemoveField(
            model_name="shiftslot",
            name="start",
        ),
        migrations.RemoveField(
            model_name="shiftslot",
            name="type",
        ),
        migrations.RemoveField(
            model_name="shifttrade",
            name="shift_offer",
        ),
        migrations.RemoveField(
            model_name="shifttrade",
            name="shift_taker",
        ),
        migrations.RemoveField(
            model_name="shifttrade",
            name="signed_off_by",
        ),
        migrations.AddField(
            model_name="shift",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="shift",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.shift",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filled_shifts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shifttrade",
            name="shift",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trades",
                to="schedules.shift",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shifttrade",
            name="status",
            field=models.CharField(
                choices=[
                    ("OFFERED", "Offered"),
                    ("REQUESTED", "Requested"),
                    ("COMPLETE", "Complete"),
                ],
                default="OFFERED",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="shifttrade",
            name="verified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="schedule",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="schedules.schedule",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shifttrade",
            name="offeror",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_trades_offered",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shifttrade",
            name="taker",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_trades_taken",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("schedule", "location")},
        ),
        migrations.DeleteModel(
            name="ShiftSlotGroup",
        ),
        migrations.DeleteModel(
            name="ShiftSlotGroupDayRule",
        ),
        migrations.DeleteModel(
            name="ShiftSlotGroupInterest",
        ),
        migrations.DeleteModel(
            name="ShiftSlotTemplate",
        ),
        migrations.DeleteModel(
            name="ShiftTradeOffer",
        ),
        migrations.DeleteModel(
            name="UserShift",
        ),
    ]
