# Generated by Django 3.2.13 on 2022-09-12 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0026_auto_20220913_0012"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                        ],
                        max_length=32,
                    ),
                ),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                (
                    "schedule_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.scheduletemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "shift slot group templates",
            },
        ),
        migrations.RemoveField(
            model_name="shiftslotgrouptemplate",
            name="schedule_template",
        ),
        migrations.DeleteModel(
            name="ScheduleSlotType",
        ),
        migrations.DeleteModel(
            name="ShiftSlotGroupTemplate",
        ),
    ]
