# Generated by Django 3.2.13 on 2022-09-13 15:07

from django.db import migrations


def delete_schedule_models(apps, schema_editor):
    Schedule = apps.get_model("schedules", "Schedule")
    Shift = apps.get_model("schedules", "Shift")
    ShiftSlot = apps.get_model("schedules", "ShiftSlot")
    ScheduleTemplate = apps.get_model("schedules", "ScheduleTemplate")
    ShiftTemplate = apps.get_model("schedules", "ShiftTemplate")
    Schedule.objects.all().delete()
    Shift.objects.all().delete()
    ShiftSlot.objects.all().delete()
    ScheduleTemplate.objects.all().delete()
    ShiftTemplate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0027_auto_20220913_0017"),
    ]

    operations = [
        migrations.RunPython(
            delete_schedule_models, reverse_code=migrations.RunPython.noop
        ),
    ]
