# Generated by Django 3.2.13 on 2022-09-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0028_auto_20220913_1707"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleRole",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="schedules.schedule",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="shift",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("RUNDHALLEN", "Rundhallen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shiftslot",
            name="role",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="shift_slots",
                to="schedules.schedulerole",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ShiftSlotTemplate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField()),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.schedulerole",
                    ),
                ),
                (
                    "shift_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schedules.shifttemplate",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "shift slot templates",
                "unique_together": {("shift_template", "role")},
            },
        ),
    ]
