# Generated by Django 3.2.13 on 2022-09-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0030_auto_20220913_1718"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedulerole",
            unique_together={("schedule", "name")},
        ),
    ]
