# Generated by Django 3.2.13 on 2022-09-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0032_auto_20220927_2050"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="shiftslottemplate",
            options={"verbose_name_plural": "Shift slot templates"},
        ),
        migrations.AlterModelOptions(
            name="shifttemplate",
            options={"verbose_name_plural": "Shift templates"},
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="day",
            field=models.CharField(
                choices=[
                    ("MONDAY", "Monday"),
                    ("TUESDAY", "Tuesday"),
                    ("WEDNESDAY", "Wednesday"),
                    ("THURSDAY", "Thursday"),
                    ("FRIDAY", "Friday"),
                    ("SATURDAY", "Saturday"),
                    ("SUNDAY", "Sunday"),
                ],
                help_text="Day of the week this shift occurs",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="shifttemplate",
            name="name",
            field=models.CharField(
                help_text="Name that will be applied to the generated shift",
                max_length=100,
            ),
        ),
    ]
