# Generated by Django 3.2.13 on 2022-09-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0033_auto_20220928_1640"),
    ]

    operations = [
        migrations.AddField(
            model_name="shifttemplate",
            name="location",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDGAR", "Edgar"),
                    ("BODEGAEN", "Bodegaen"),
                    ("RUNDHALLEN", "Rundhallen"),
                    ("KLUBBEN", "Klubben"),
                    ("LYCHE_BAR", "Lyche Bar"),
                    ("LYCHE_KJOKKEN", "Lyche Kjøkken"),
                    ("STORSALEN", "Storsalen"),
                    ("SELSKAPSSIDEN", "Selskapssiden"),
                    ("STROSSA", "Strossa"),
                    ("DAGLIGHALLEN_BAR", "Daglighallen Bar"),
                ],
                max_length=64,
                null=True,
            ),
        ),
    ]
