# Generated by Django 3.2.13 on 2022-09-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0035_alter_shifttemplate_schedule_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslottemplate",
            name="shift_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shift_slot_templates",
                to="schedules.shifttemplate",
            ),
        ),
    ]
