# Generated by Django 3.2.13 on 2022-09-29 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0036_alter_shiftslottemplate_shift_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shift",
            name="schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="schedules.schedule",
            ),
        ),
    ]
