# Generated by Django 3.2.13 on 2022-10-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0039_auto_20221003_0158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftslot",
            name="role",
            field=models.CharField(
                choices=[
                    ("BARISTA", "Barista"),
                    ("KAFEANSVARLIG", "Kaféansvarlig"),
                    ("BARSERVITOR", "Barservitør"),
                    ("HOVMESTER", "Hovmester"),
                    ("KOKK", "Kokk"),
                    ("SOUSCHEF", "Souschef"),
                    ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                    ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                    ("BRYGGER", "Brygger"),
                    ("BARTENDER", "Bartender"),
                    ("BARSJEF", "Barsjef"),
                    ("SPRITBARTENDER", "Spritbartender"),
                    ("SPRITBARSJEF", "Spritbarsjef"),
                    ("UGLE", "Ugle"),
                    ("BRANNVAKT", "Brannvakt"),
                    ("RYDDEVAKT", "Ryddevakt"),
                    ("SOCIVAKT", "Socivakt"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="shiftslottemplate",
            name="role",
            field=models.CharField(
                choices=[
                    ("BARISTA", "Barista"),
                    ("KAFEANSVARLIG", "Kaféansvarlig"),
                    ("BARSERVITOR", "Barservitør"),
                    ("HOVMESTER", "Hovmester"),
                    ("KOKK", "Kokk"),
                    ("SOUSCHEF", "Souschef"),
                    ("ARRANGEMENTBARTENDER", "Arrangementbartender"),
                    ("ARRANGEMENTANSVARLIG", "Arrangementansvarlig"),
                    ("BRYGGER", "Brygger"),
                    ("BARTENDER", "Bartender"),
                    ("BARSJEF", "Barsjef"),
                    ("SPRITBARTENDER", "Spritbartender"),
                    ("SPRITBARSJEF", "Spritbarsjef"),
                    ("UGLE", "Ugle"),
                    ("BRANNVAKT", "Brannvakt"),
                    ("RYDDEVAKT", "Ryddevakt"),
                    ("SOCIVAKT", "Socivakt"),
                ],
                max_length=64,
            ),
        ),
    ]
