# Generated by Django 3.2.14 on 2022-10-05 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0041_schedule_display_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="generated_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts_generated",
                to="schedules.scheduletemplate",
            ),
        ),
    ]
