# Generated by Django 3.2.16 on 2023-01-03 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("migrated_from_sg", models.BooleanField(default=False)),
                ("approved", models.BooleanField(default=False)),
                ("context", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "verbose_name_plural": "quotes",
                "ordering": ["created_at"],
                "permissions": (
                    ("approve_quote", "Can approve quotes"),
                    ("invalidate_quote", "Can invalidate quotes"),
                ),
            },
        ),
        migrations.CreateModel(
            name="QuoteVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.SmallIntegerField()),
            ],
            options={
                "verbose_name_plural": "quote votes",
            },
        ),
    ]
