# Generated by Django 3.2.16 on 2022-12-04 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotevote",
            name="caster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quote_votes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quotevote",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="quotes.quote",
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="reported_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="reported_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tagged",
            field=models.ManyToManyField(
                blank=True, related_name="quotes", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddIndex(
            model_name="quotevote",
            index=models.Index(fields=["quote"], name="quotes_quot_quote_i_8242ee_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="quotevote",
            unique_together={("quote", "caster")},
        ),
    ]
