# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'verbose_name_plural': 'quotes'},
        ),
        migrations.AlterModelOptions(
            name='quotevote',
            options={'verbose_name_plural': 'quote votes'},
        ),
        migrations.AlterField(
            model_name='quote',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['verified_by'], name='quotes_quot_verifie_1bba3d_idx'),
        ),
        migrations.AddIndex(
            model_name='quotevote',
            index=models.Index(fields=['quote'], name='quotes_quot_quote_i_8242ee_idx'),
        ),
    ]
