# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 20:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotevote',
            name='caster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quotevote',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='quotes.Quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='quoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quote',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verified_quotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='quotevote',
            index=models.Index(fields=['quote'], name='quotes_quot_quote_i_8242ee_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotevote',
            unique_together=set([('quote', 'caster')]),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['verified_by'], name='quotes_quot_verifie_1bba3d_idx'),
        ),
    ]
