# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 13:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0002_auto_20171120_1301'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quotevote',
            unique_together=set([('quote', 'caster')]),
        ),
    ]
