# Generated by Django 2.1.2 on 2018-11-21 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0006_auto_20181121_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'quotes'},
        ),
    ]
