# Generated by Django 2.1.2 on 2018-12-04 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_auto_20181121_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'quotes'},
        ),
    ]
