# Generated by Django 2.2 on 2019-04-22 16:27

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0008_auto_20181204_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['created'], 'verbose_name_plural': 'quotes'},
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='created_at',
            new_name='created',
        ),
        migrations.AlterField(
            model_name='quote',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='quote',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
