# Generated by Django 3.1.7 on 2021-05-02 10:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0009_auto_20190721_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quoter',
        ),
        migrations.AddField(
            model_name='quote',
            name='quoter',
            field=models.ManyToManyField(blank=True, related_name='quotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
