# Generated by Django 3.1.7 on 2021-05-02 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0010_auto_20210502_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quoter',
            new_name='tagged',
        ),
    ]
