# Generated by Django 2.1.7 on 2019-07-13 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quotes', '0010_auto_20190221_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reported_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='reported_quotes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
