# Generated by Django 3.2.5 on 2021-12-02 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0011_auto_20210502_1739"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={"ordering": ["created_at"], "verbose_name_plural": "quotes"},
        ),
        migrations.RemoveField(
            model_name="quote",
            name="created",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="modified",
        ),
        migrations.AddField(
            model_name="quote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
