# Generated by Django 3.2.12 on 2022-02-28 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0013_alter_quotevote_caster"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quote",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
