# Generated by Django 3.2.16 on 2022-10-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0014_alter_quote_created_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegacyQuote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_created", models.DateTimeField()),
                ("text", models.TextField()),
            ],
        ),
    ]
