# Generated by Django 3.2.16 on 2022-11-14 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quotes", "0016_auto_20221025_2005"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="quote",
            name="quotes_quot_verifie_1bba3d_idx",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="verified_by",
        ),
        migrations.AddField(
            model_name="quote",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="quote",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_quotes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
