# Generated by Django 3.2.16 on 2022-11-14 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0017_auto_20221115_0004"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LegacyQuote",
        ),
    ]
