# Generated by Django 3.2.16 on 2022-11-16 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0018_delete_legacyquote"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={
                "ordering": ["created_at"],
                "permissions": (
                    ("approve_quote", "Can approve quotes"),
                    ("invalidate_quote", "Can invalidate quotes"),
                ),
                "verbose_name_plural": "quotes",
            },
        ),
    ]
